src/wx/guiinit.cpp
src/wx/panel.cpp

Switch to fullscreen after the game starts so that the GUI does not fall over.

---

src/gba/GBA.cpp
src/gba/bios.cpp
src/gba/bios.h

This patch adds those missing HLE BIOS functions for sound driver: https://sourceforge.net/p/vbam/bugs/24/
It is utilized by Phantasy Star Collection at intro. I don't know any other games using this BIOS driver, so I just implemented the parts that Phantasy Star Collection uses.
This patch is far away from perfect yet. Sound quality is not the same as with original BIOS. Also code is horrible to read, since I just kept translating arm instructions to C without thinking too much. Got it done quickly so if anyone has keen interest on continuing from here.
Patch by Juha Laukkanen

HLE BIOS functions for sound driver

---

src/gba/Cheats.cpp

Compilation failed for me without the explicit cast.

Added cast to uint8

---

todo.md

Some stuff I would like to wrap up from the Mac port and some longer
term things as well.

some TODO entries from me

---

README.md
fex/7z_C/7zAlloc.c
fex/fex/Data_Reader.cpp
src/common/ffmpeg.cpp
src/gb/gbPrinter.cpp
src/gba/GBA-thumb.cpp
src/gba/GBA.cpp
src/gba/GBALink.cpp
src/gba/remote.cpp
src/wx/bin2c.c

I was cleaning up some gcc warnings and I found a couple other issues. The commit messages should be self-explanatory, but let me know if clarification is needed.
I've only tested building it on Linux, so please let me know if it breaks anything else.

Various fixes

---

src/gba/elf.cpp

fix some potential buffer-overflows

---

src/wx/panel.cpp

When render_method is set to simple and filters are enabled, DrawArea dimension code makes bad assumptions about draw bounds. Make sure that stuff is actually drawn starting where it should

Fixed filter draw bounds

---

src/wx/panel.cpp

Draw height is still not consistent across render modes and filter settings. Ensure that windows are actually drawn to the proper height and contents are drawn to fit

Fix draw height across rendering modes

---

installdeps

rename cmake directory in installdeps from one that doesn't exist

Fix cmake directory in installdeps

---

src/wx/panel.cpp

start drawing at the top of the screen and handle weird cases where filters are inconstant between draw methods. vertical draws should now be correct and pixel perfect regardless of filter settings and output module

Finalize vertical draw fixes and code cleanup

---

src/libretro/libretro.cpp

Fixes https://github.com/visualboyadvance-m/visualboyadvance-m/issues/240

libretro: Fix save types not properly set using overrides

---

src/gba/Cheats.cpp

fixes https://github.com/visualboyadvance-m/visualboyadvance-m/issues/226

Fix cheats not working in GBA

---

installdeps

add zip, needed during compile

debian: update dependency

---

src/libretro/libretro.cpp

support for multiline cheats for gb/gbc, add turbo buttons

Libretro : cheat updates and tubo buttons

---

src/gb/GB.cpp
src/gb/gbGfx.cpp

Some quick fixes for these asan issues:
e0cf521 - https://github.com/visualboyadvance-m/visualboyadvance-m/issues/360#issuecomment-459556302
ed0e02d - https://github.com/visualboyadvance-m/visualboyadvance-m/issues/360#issuecomment-459556825

some asan-related fixes

---

src/wx/wxvbam.cpp

@rkitover Sorry about this. I committed the fix in the wrong branch and only now realized that.

Fix to set correctly position Y for geometry of gui window.

---

src/wx/opts.cpp
src/wx/xrc/SoundConfig.xrc

- global implementation has set max at 200% (2.0 float), its already loud enough at 100%

wx: Change max volume from 400 to 200

---

src/gba/GBA.cpp
src/gba/GBAinline.h
src/gba/Sound.cpp
src/gba/Sound.h

- minor, non-function changing updates like float value changes, some unrolled sections
- break soundEvent into separate 8 / 16 bit data writes.

Sound.cpp: Update

---

src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/widgets/keyedit.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h
src/wx/xrc/MainMenu.xrc

@rkitover This is the fix for everything from that deleted user (whose issues were also erased). I believe each commit explains itself, so I will just post some comments on the code.
You should probably check the design, since I also had to do some `FIXME` from the code.
I will see if there is something related on our issues section.

Key bindings and shortcuts improvement.

---

src/common/ConfigManager.cpp

this fixes the build process but shouldn't interfere with gcc

Just a minor issue with clang and snprintf on windows

---

src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/sys.cpp
src/wx/wxvbam.h
src/wx/xrc/MainMenu.xrc

@rkitover All the issues opened by this user are fun too code. I tested this on `Super Mario Land` (GB).
This is based on `vba-rr` (as in done the same way).
I also had to do some fixes, but attached them here because only discovered them while coding this.

Auto hold buttons.

---

.travis.yml

This cleans up the `.travis.yml` file to be easier to read and modify with less redundant sections. There should be no change in behavior.

travis: Refactor script.

---

.travis.yml

Trivial clean up and follow up to PR https://github.com/visualboyadvance-m/visualboyadvance-m/pull/527.

travis: Clean up.

---

src/common/ConfigManager.cpp
src/gba/GBALink.cpp
src/gba/GBALink.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/widgets/wxmisc.cpp
src/wx/xrc/NetLink.xrc

This adds a field to set the link network port and sets the default timeout to 500ms, repairing the previous default of 1ms.
@denisfa @negativeExponent would love to know what you guys think.

Minor link improvements

---

src/gba/agbprint.cpp

@rkitover This is for #269. The functions seem to be correct. We were just missing the output to our log window.

Make AGBPrint output to our Logging window.

---

DEVELOPER-MANUAL.md

Document how we interact with transifex and how to pass strings to
non-wxWidgets code.

Add to dev manual on translations and char sets.

---

src/Util.cpp

@rkitover This is my fault since #622. I don't remember if I did not test the png format for screen capture or tested something else. This time I did, so it is working.

Fix PNG capture screen.

---

src/gb/GB.cpp
src/gba/GBA.cpp
src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/strutils.cpp
src/wx/strutils.h
src/wx/viewsupt.cpp
src/wx/widgets/joyedit.cpp
src/wx/widgets/keyedit.cpp
src/wx/widgets/wx/joyedit.h
src/wx/widgets/wx/keyedit.h
src/wx/wxhead.h
src/wx/wxutil.cpp
src/wx/wxutil.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h
src/wx/xrc/AccelConfig.xrc

@rkitover I have been busy these times, so I was very slow to contribute. Not so sure when it is going to get better, but I will try to finish some WIPs.
There is a couple of things here, one small issue with turbo and input refactoring. Tell me what you think about these.
You have a russian keyboard layout, right? Could you check if this works for you? My testing was with the `Ç` and variations, so at least I have something working right now.
EDIT1: I will fix the CI/CD later. I know what to do.
EDIT2: Not sure what is happening with github right now, I added a commit but it did not appear here.

Mainly input refactoring.

---

src/wx/panel.cpp

Followup on baa0341b.
Reintroduce checking if a key is actually pressed in the panel OnKeyDown
event with wxGetKeyState(key_code).
Introduced in b0ec846 and removed in baa0341b.
wxGetKeyState() does not work on Wayland and does not work for Unicode
keys, support for which was introduced in baa0341b, which is why the
call was removed.
Add two static functions is_key_pressed(ev) and is_key_released(ev) that
return true under Wayland or if the key is Unicode, and call
wxGetKeyState() otherwise.
The reason this call was introduced in b0ec846 was to work around a bug
in some Linux distributions that caused spurious keyboard events to be
generated. The bug apparently still persists, see #689.
Because the two additional checks were necessarily added, the bug may
persist on Wayland, if it exists …

Check game kbd input with wxGetKeyState() again.

---

src/gba/GBA-arm.cpp
src/gba/GBA-thumb.cpp
src/gba/GBA.cpp
src/gba/bios.cpp

This should solve #695, at least that was the result from my testing.

GBA bios improvement.

---

po/wxvbam/wxvbam.pot
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This adds a command-line option to specify a custom configuration file.

Add an option to set a configuration file

---

src/wx/cmdevents.cpp

Force a panel update when configuring bilinear.

---

.github/ISSUE_TEMPLATE/bug_report.yml

encourage users to search for existing issues

  encourage users to search for existing issues in bug report template

---

.github/ISSUE_TEMPLATE/feature.yml

Add before creating request to feature.yml

---

src/wx/widgets/sdljoy.cpp

Previously, a manual polling of every joystick was performed every 25ms,
resulting in many CPU resources being wasted. This seems to have been
put in place to deal with issues in SDL where joysticks connected after
SDL was initialized did not fire SDL events properly. From manual
testing, this issue seems to have been fixed.
This also fixes a bug in handling of legacy joystick hats, where an
incorrect conversion for the event value was performed.
Finally, this fixes minor typoes and renames
`wxSDLJoyState::ProcessEvent()` to `wxSDLJoyState::ProcessSDLEvent()` to
suppress a warning about a method override.

Remove manual joystick polling

---

README.md

change invite code

---

src/common/memgzio.c

[build] Fix warnings in memgzio.c

---

src/common/ConfigManager.cpp
src/common/Patch.cpp
src/common/SoundSDL.cpp
src/common/dictionary.c

[build] Fix warnings in src/common

---

CMakeLists.txt
src/wx/CMakeLists.txt

* Add /ZI compiler flag in Debug mode to get proper debug symbols.
* Specify hidpi support in the app manifest.

[build][msvc] Fix debug information and set hidpi support

---

.gitignore
README.md
cmake-variants.yaml
cmake/Set-Toolchain-vcpkg.cmake
vscode/settings.json

* Infer the VCPKG triplet for MSVC-like environments.
* Add recommended VS Code settings.
* Add instructions for using clangd.

[build] Add VS Code integration

---

CMakeLists.txt
cmake/Architecture.cmake
cmake/HostCompile.cmake
cmake/MSVC_x86_Host_Compile.cmake
installdeps
src/wx/CMakeLists.txt

@Steelskin I'm building with `-DCMAKE_CXX_FLAGS=-DNO_OGL` until I add your wxwidgets port patch.

Arm64 msvc cross

---

src/wx/cmdevents.cpp

Resolves assertions when opening the dialog windows.

Fix Start Record/Play for emulator native recordings.

---

src/wx/config/option.h
src/wx/widgets/wx/wxmisc.h
src/wx/wxhead.h

Include cstdint for wx

---

po/wxvbam/wxvbam.pot
src/wx/cmdevents.cpp
src/wx/config/internal/option-internal.cpp
src/wx/config/option-id.h
src/wx/config/option-proxy.h
src/wx/config/option.h
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This introduces a new INI config option called "IniVersion". Whenever default values change or options are renmaed, the latest version number is incremented and an update path is run.
This change also rewrites part of the initialization routine by adding more safety checks before creating or reading the configuration file.

Add INI file versioning

---

src/gb/GB.cpp

Also seperates HUC1 from MBC1
Closes #1084

Implements sav File Read/Writes for HUC3

---

src/vba-over.ini

despite not having backup ram.

workaround for Stuart Little 2 crashing when set to none

---

src/gba/GBALink.cpp

Some software (like the EU version of Digimon Racing) relies on the SIOCNT register being properly updated when no cable is connected. Otherwise, they risk getting stuck in a loop waiting for an update on the SIOCNT register.

Update SIOCNT when the link driver is disconnected

---

src/gb/gbCartData.cpp

Further testing showed some limitations with the current GB header parsing. Many homebrew and some licensed cartridges do not follow the expected format. In particular, the manufacturer code used in the "new format" is not always used properly.
Some mapper flags seem to not actually exist in practice. These have been documented as comments.
The header parsing code was creating string objects with '\0' bytes, this is now properly sanitized.
The destination code flag was not being set properly. This has been fixed.

Sanitize and improve the GB header parsing

---

src/System.h
src/gba/Sound.cpp
src/gba/Sound.h
src/libretro/libretro.cpp
src/sdl/ConfigManager.cpp
src/wx/cmdevents.cpp
src/wx/config/internal/option-internal.cpp
src/wx/config/option-proxy.h
src/wx/guiinit.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

* Moves most remaining options toggled by menu items to g_owned_opts and modifies associated usage.
* Adds more obervers to handle option changes.

Move more options to g_owned_opts

---

src/gba/GBAGfx.h

This was fixed by endrift in mGBA in commit
https://github.com/mgba-emu/mgba/commit/4ce9b83362ad66b1421afea7372adfc753bce97c
Fixes #1130

[GBA] Do not draw BG tiles from outside of BG VRAM

---

CMakeLists.txt
cmake/Set-Toolchain-vcpkg.cmake
src/wx/CMakeLists.txt

Newer github actions bot setup no longer include a powershell.exe binary, only pwsh.exe

[CI] Look for pwsh in addition to powerhsell

---

CMakeLists.txt
src/common/SoundSDL.h

The variable name should have been changed to SDL2_INCLUDE_DIRS

[CI] Properly inclue SDL2 directories for vbamcore

---

src/common/ffmpeg.h
src/filters/hq/c/hq_shared.h
src/sdl/filters.cpp
src/wx/config/user-input.cpp
src/wx/strutils.h

Fix various warnings in filters and headers

---

src/apu/Effects_Buffer.cpp
src/apu/Effects_Buffer.h
src/common/dictionary.c
src/common/ffmpeg.cpp
src/filters/xBRZ/xbrz.cpp
src/gb/GB.cpp
src/gba/BreakpointStructures.cpp
src/gba/GBA.cpp
src/gba/GBALink.cpp
src/gba/GBAinline.h
src/gba/Sound.cpp
src/sdl/SDL.cpp
src/wx/dialogs/display-config.cpp
src/wx/widgets/checkedlistctrl.cpp
src/wx/widgets/wx/checkedlistctrl.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

Fix most remaining release warnings

---

CMakeLists.txt
cmake/MakeReleaseCommitAndTag.cmake
cmake/Set-Toolchain-vcpkg.cmake
cmake/UpdateAppcast.cmake
src/wx/CMakeLists.txt

[Build] Make powershell optional on non-Windows

---

.github/workflows/macos-build.yml
.github/workflows/msys2-build.yml
.github/workflows/ubuntu-build.yml
.github/workflows/visual-studio-build.yml
src/libretro/Makefile
src/libretro/link.T

This reworks the CI coverage to add `TRANSLATIONS_ONLY=ON` and libretro builds to GitHub Actions.

[Build] Improve CI build coverage

---

src/wx/audio/internal/faudio.cpp

This removes remaining dependencies on Windows in the FAudio code by removing the device notification code and switching to portable `condition_variable` for the buffer end notification event.

[FAudio] Switch to portable `condition_variable`

---

.github/workflows/msys2-build.yml
src/wx/config/CMakeLists.txt
src/wx/config/bindings-test.cpp
src/wx/config/bindings.cpp
src/wx/config/bindings.h
src/wx/config/cmdtab.cpp
src/wx/config/cmdtab.h
src/wx/config/command.cpp
src/wx/config/internal/bindings-internal.cpp
src/wx/dialogs/accel-config.cpp
src/wx/opts.cpp

In addition to fixing a couple of minor bugs, this also creates some utility functions to access the cmdtab data.

[Test] Add tests for the Bindings class

---

.gitmodules

This will help make older builds reproducible.

[win32-deps] Use specific commit in submodule

---

src/core/gba/gba.cpp

reallocate the updated size instead of the constant size

---

cmake/Options.cmake
src/core/gba/gbaLink.cpp
src/core/gba/gbaLink.h
src/core/gba/internal/gbaSockClient.cpp
src/core/gba/internal/gbaSockClient.h
src/wx/guiinit.cpp

Make some changes for the SFML Network library for the 3.x APIs.
Builds now, needs testing and review.

Update Link SFML usage to SFML 3.x APIs

---

tools/builder/core.sh

This just updates a good portion of the core packages that the build scripts use to build against.

BUILDER: Updated core.sh source packages required to build vba-m

---

src/components/av_recording/av_recording.cpp

Fix AVCodec deprecations

---

src/core/gb/gb.cpp
src/core/gba/gba.cpp

also fixes the bouncing cgb bios issue

24bit was prone to corrupting g_pix on all renderers

---

src/core/gb/gbGfx.cpp
src/wx/gfxviewers.cpp

Fixed with Claude.
Closes #650, #539

Fix DMG OBP layer in CGB and GBA modes
