visualboyadvance-m/visualboyadvance-m

src/common/ConfigManager.cpp
src/wx/wxvbam.cpp

I'm probably going to push more commits to this PR soon, in particular to fix the Esc key, maybe other stuff.
Write vbam.ini to ~/Library/Application Support/vbam on OSX.
Do not create ~/.vbam on OSX in common/ConfigManager.cpp .
Make get_config_path and wxvbamApp::GetConfigurationPath return
directories with a writable parent in reverse search order when no
writable directories in the current search order are available since the
directory is created in OnInit.
This prefers to create the user-local directory and write the vbam.ini
there.

fix configuration directory on OSX

---

src/common/ffmpeg.cpp
src/wx/cmdevents.cpp

FFmpeg 3.0 removed a significant chunk of legacy code VBA-M was relying on. I hammered on it a bit, got it compiling again, and got audio recording working again. Video recording doesn't work with ffmpeg 3.0 still, however.
This is probably not at all the way this should be done, but it at least provides a place to start. None of this code should come into effect if compiled with older versions of ffmpeg.

Kludges for ffmpeg 3.0

---

CMakeLists.txt
src/wx/CMakeLists.txt

This makes these files show up in generated CodeBlocks projects, which makes life easier for folks who import into QtCreator.
I've only done this for the WX build and some stuff in the main CMakeLists.txt, as I currently cannot test any changes I make to other builds.

Add some header and resource files to CMakeLists.txts (Core+WX)

---

src/sdl/SDL.cpp

Previously this function returned true for `if(saveDir)` when `saveDir` was simply a zero length string following a branch that returned `/<savepath>` which doesn't work when the user isn't a root user.

Edit sdlStateName, fixing SDL states on a Mac

---

src/common/SoundSDL.h

It seems like most of the types are moving to fixed width integer types and this file wasn't fully converted.

Fixing U16 and U8 Parameter Types

---

fex/fex/blargg_common.h

This PR fixes several instances of a casting/conversion error in GCC6
`error: invalid conversion from 'int' to 'blargg_err_t {aka const char*}' [-fpermissive]`
Unrelated: I see you're working on changing all the instances of `u8` to `uint8_t` and such, but your last commit was on the 9th. If you'd like, I can take a shot at getting the master branch into a compilable state until you can resume work.

Fix a casting error in GCC 6

---

CMakeLists.txt

Currently, the build is broken on Linux as fixed width integers (for example uint32) are used via <cstdint> without a namespace. This is officially only allowed in C++11 and later.
See http://en.cppreference.com/w/cpp/types/integer for details.
Without the commit, I am currently forced to set my CXX_FLAGS to include "-std=c++11" if I don't want to get those errors:
```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/cstdint:35:0,
from /workspace/visualboyadvance-m/src/System.h:4,
from /workspace/visualboyadvance-m/src/Util.cpp:23:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled …
```

Set requirement to C++11 in cmake 

---

.clang-format

I noticed this very small discrepancy, and so I changed it.  The `CMakeLists` is already using C++11 standard, but the `.clang-format` was not.

Small change: make `.clang-format` use C++11 Standard

---

.gitignore
src/gba/GBASockClient.cpp
src/gba/GBASockClient.h

see: http://dev.vba-m.com/T2
> Every time I launch a server it defaults to the locahost IP instead of my
> actual IP. This is preventing me from linking with friends over Hamachi. When
> they enter my IP it errors on their end and they cannot connect. [report taken
> from <https://sourceforge.net/p/vbam/bugs/219/>]
Also, by chance, added the build folder to `.gitignore` so as to not pollute the
git repo.  I meant to do them as separate commits, but I forgot to do so.
Signed-off-by: Jonathan Sifuentes <jayands2k11@ymail.com>

Fix for T2

---

src/wx/openal.cpp
src/wx/opts.cpp

Fix the dynamic library path for OpenAL to the framework included with
OS X.
Make option initialization set the AudioAPI to OpenAL on mac by default,
since SDL sound is currently completely broken.
There is a lot of stuttering, will have to look at that next.

improve OpenAL support on Mac and make it default

---

src/wx/xrc/MainMenu.xrc

On OS X, the F11 key is by default bound to "show desktop", so is a poor
choice for the "ToggleFullscreen" accelerator.
The default key combo to take apps fullscreen should be Ctrl+Cmd+F
according to:
https://support.apple.com/kb/PH18744?locale=en_US
Fortunately, this was very easy to fix by using the "platform" attribute
in MainMenu.xrc .
NOTE: this does not give us "real" OS X fullscreen yet, where the app is
on its own space, like native fullscreen apps. In the future it would be
nice to add an option to do this.

rebind toggle fullscreen on mac

---

CMakeLists.txt
src/wx/CMakeLists.txt
src/wx/drawing.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

Use a high-res surface on HiDPI (e.g. retina) Macs for the OpenGL
renderer, and scale window accordingly. Also fix fullscreen toggle not
working in HiDPI mode. And some other stuff.
Aside from the .app not being linked statically, the app is now fully
functional on Mac and ready to ship.
Full change details:
* add -DDEBUG or -DNDEBUG based on CMAKE_RELEASE_TYPE
* properly search for homebrew/macports/fink directories, and only add
them if they exist
* fix building with wx debug support, when available
* use explicit OpenGL context on Mac too for new versions of wx
* add main_frame pointer in GameArea back to MainFrame, and a
SetMainFrame(MainFrame* parent) public method to set it in guinit
* add full support for reading and writing double value config options
(the GUI still needs to be …

Mac OS X HiDPI fixes + other misc

---

src/wx/drawing.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

Only load config files with the app name set to "visualboyadvance-m" on
Windows and Mac, on unix keep the default of "vbam" for now so that
users' ~/.vbam directories are found correctly.
TODO:
* migrate all of this properly to XDG paths on unix, giving users the
option to move their config

fix backcompat on unix for config brkn in 7a7a72f

---

src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/xrc/DisplayConfig.xrc

Change the Scale control in the DisplayConfig dialog from a SpinCtrl to
a TextCtrl (for a simple text field) because GenericValidator does not
support using a double* with a SpinCtrl.
Also force adjustment on minimum size and resize the window when
necessary on panel creation, so that when the user sets the value
higher, the window size automatically adjusts.

fix DisplayConfig panel brkn in 7a7a72f

---

src/wx/CMakeLists.txt
src/wx/drawing.h
src/wx/opts.cpp
src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

After creating the drawing panel, call SetFocus() on it and use
Connect() to bind keyboard events from it. Add the wxWANTS_CHARS flag to
all DrawingArea subclasses so that wxEVT_CHAR_HOOK can be used instead
of wxEVT_KEY_DOWN, because it is more general and catches more keys.
Change the process_key_press function to return a bool indicating
whether a game control is currently pressed or not, this is used in the
key events to determine whether the event should be propagated or not.
If in a game key, do not propagate the event, otherwise it hits one of
the other controls and generates a beep sound.
The menu open/closed/highlighted events had to be turned off for Mac,
because the menubar is catching all keyboard events for some reason even
before they reach the drawing panel event handler. …

fix kbd controls on Mac + misc.

---

src/wx/CMakeLists.txt

Instead of checking if CMAKE_BUILD_TYPE is "Release", check that it is
**NOT** "Debug", because by default CMAKE_BUILD_TYPE is empty.

fix Mac post-build bundle/link broken in a775cc4

---

src/System.h
src/common/Patch.h
src/common/Port.h
src/common/cstdint.h
src/gb/gbGlobals.cpp
src/gb/gbGlobals.h
src/gb/gbMemory.h
src/gba/BreakpointStructures.h
src/gba/EEprom.h
src/gba/Flash.h
src/gba/GBA.h
src/gba/GBASockClient.h
src/gba/Sram.h
src/libretro/libretro.cpp
src/sdl/SDL.cpp
src/sdl/filters.h
src/wx/panel.cpp
src/wx/tools/osx/third_party_libs_tool
src/wx/viewers.cpp

Make a custom cstdint.h header file that includes <tr1/cstdint> if
<cstdint> is not available, because the clang 3.x used on Lion does not
have it. Change all references to <cstdint> to use it instead.
Add missing OpenGL header for older OS X in sdl/SDL.cpp .
When calling HiDPI methods, use respondsToSelector: to check if the
methods are available first.
Fix the bundling/linking script to support multiple copies of the same
dylib with different versions. Necessary to include both the Lion system
libpng and the brew libpng. Including the system libpng is necessary
because it is removed in later versions of OS X.

Mac OS X 10.7 (Lion) build and runtime support

---

CMakeLists.txt
src/wx/CMakeLists.txt
src/wx/macsupport.mm
src/wx/panel.cpp
src/wx/wxvbam.h

Move Objective-C++ Mac code for Wx into macsupport.mm with stub methods
in panel.cpp, and stop compiling all C++ as Objective-C++.
cmake -G Xcode # now works fine

fix Xcode project generation via cmake

---

src/wx/panel.cpp
todo.md

Pass the keyboard modifiers to process_key_press so that it only
registers a game key if the modifiers match. That is, if e.g. ENTER is a
game key, then ALT+ENTER gets passed to other Wx controls and does not
register as a game key.

fix wx kbd accels that are game key + modifier

---

CMakeLists.txt

Without this change, if you don't have SFML, it'll try to build and then fail because it can't find the SFML headers.

SFML is required for link support.

---

CMakeLists.txt
CMakeScripts/FindSFML.cmake
installdeps-msys2
src/wx/CMakeLists.txt
todo.md

* Enable ffmpeg by default only on linux and msys2, it will be disabled
for normal windows builds and on mac.
* Set SFML_STATIC_LIBRARIES only for normal non-msys2 windows builds,
because msys2 does not currently have static versions of the SFML
sub-libraries, e.g. system, network, etc.. Dynamic linking works fine
for now.
* Fix quoting for -DLOCALEDIR, on windows spaces were causing errors in
make on msys2.
* Update to upstream FindSFML.cmake .
* Add an ./installdeps-msys2 script to install all necessary tools and
libraries on msys2 for building both 64 and 32 bit windows Wx binaries.
* Add the dependencies/mingw-xaudio/include directory to
INCLUDE_DIRECTORIES so that XAudio compiles on msys2, as mingw-w64 does
not currently have XAudio headers. Also check that the user pulled the
git …

msys2 build improvements

---

src/wx/panel.cpp

Fixed an issue I was having with my gamepad where VBA wouldn't recognize that a d-pad diagonal was released until the d-pad was released entirely (which I think is the same as issue #42).
The value in ev.GetControlValue() comes from the SDL function function SDL_JoystickGetHat(), which returns a bitmask of the directions currently pressed, so I just used that value directly instead of a bunch of specious logic with the WXJB enums.

Fix wx joystick hat diagonals

---

src/wx/wxvbam.appdata.xml

Changing VBA-M to VisualBoyAdvance-M and fixing a bunch of warnings thrown by _appstream-util validate_. Still needs translations and screenshot(s), but it's good enough for now.
Note that metadata_license is the license for this specific file; apparently, it's not allowed to be GPL, so CC-BY-SA-3.0 is close enough.

Appdata fixes

---

CMakeLists.txt
src/common/Patch.cpp
src/gb/gbCheats.cpp
src/gba/Cheats.cpp
src/wx/cmdevents.cpp

Some misc fixes:
- Fix some GCC warnings and added some error cases/checking
- fpermissive is not a C flag, only a c++ flag. I've removed it to silence a warning.
- cheatsImportGSACodeFile incorrectly returns false in non-error case, should be true for success (see src/wx/cmdevents.cpp). Caused an incorrect error code to print.

Fix GCC warnings, incorrect c flag, wrong return type

---

src/wx/cmdevents.cpp

Clicking "Report Bugs" goes to SF instead of github.
I'm assuming SF isn't being used anymore, so this should really be updated.

Fix incorrect bug tracker link

---

src/common/SoundSDL.cpp

Looks like the throttle issues for SDL was just caused by the audio device not being closed correctly. This was causing incorrect game speeds and a segfault on quit.
I also changed it so the throttle is applied on init, so the device isn't unnecessarily initialized twice (once for load, another to apply the throttle).

Fixes for SDL throttle

---

installdeps

Multiple previously specified packages are either already in system.devel or are dependencies of items such as libgtk-2-devel or libgtk-3-devel, dependencies of those dependencies, etc.

Simplified Solus installdeps

---

src/common/ConfigManager.cpp

glibc's fclose implementation does not do a NULL check and will crash on "fclose(NULL)". A bunch of Fedora users have been sending in traces for this issue. I've added a log on failure case, likely if the user does not have permission to write to the file.

Fix glibc crash: add log message on fopen failure

---

src/wx/wxvbam.cpp

Makes battery/state directory setting work when set as relative path

wx/wxvbam: fix GetAbsolutePath

---

src/wx/CMakeLists.txt

Fixes the cmake configure with `-DENABLE_FFMPEG=OFF` which was failing with this.
```
CMake Error at src/wx/CMakeLists.txt:518 (set_target_properties):
set_target_properties called with incorrect number of arguments.
-- Configuring incomplete, errors occurred!
```
Related issue. https://github.com/visualboyadvance-m/visualboyadvance-m/issues/179

cmake: Fix -DENABLE_FFMPEG=OFF

---

src/wx/opts.cpp

gopts.max_threads depends upon wxThread::GetCPUCount() returning values lower than or equal to 8 which fails on some modern CPUs (such as intel's coffee lake i7's, and ryzens r5 and r7 lines starting from the 1600). running the code on any of these CPUs or any with a higher thread count results in functions using the object to be receiving bogus values. wxThread::GetCPUCount() returning 0 threads should also be treated as bogus and set to a known safe default value

Modify max_threads sanity check to better handle erroneous values 

---

src/gba/remote.cpp

Conversion from std::string to char* is forbidden in ISO C++.

Fix forbidden conversion in remote.cpp

---

src/gba/GBA-arm.cpp

Basically this just unrolls MULL and MLAL instructions to remove use of remaining typedefs and should fix issue where an incorrect variable was used.
Fixes issue: https://github.com/visualboyadvance-m/visualboyadvance-m/issues/238

Fix some opcodes in arm

---

src/wx/cmdevents.cpp
src/wx/panel.cpp

Fix crash when adjusting echo/stereo sliders.
Fix enhancements not working when selected
Fix settings not loaded at startup
Reviews and/or modifications are welcome. Obviously, im just kinda trying out if I understand how options are linked into WX so I am not quite sure if this is the right thing to do this.

GB: Fix sound options not working

---

src/wx/panel.cpp

Set mirroring to false when rom loaded is not found in database. Making this true all the time causes some issue, for one with soft-patching some games.
Fix this https://github.com/visualboyadvance-m/visualboyadvance-m/issues/182

Set mirroringEnable to false

---

src/libretro/Makefile.common

Libretro: Do not compile arm disassembly module

---

src/gba/remote.cpp

Fixes #181 
See the steps to reproduce on the original issue. This should get remote debugging working again with gdb 8.0 which comes in the latest devkitpro.
The remote query response packets needed to be formatted slightly different and the cpsr register number is changed.

Fix remote gdb support

---

src/wx/cmdevents.cpp

When connecting the debugger the debugger variable was
being set to true before setting up the dbgMain and other related
function pointers. This caused the idle loop to attempt to call dbgMain
which was still NULL. This change makes sure that debugger isn't
set to true until all function pointers are set and that when disconnecting
the remotePort variable is reset back to 0 so we can reconnect properly.
Fixes #115

Handle debugger disconnect and reconnect properly

---

src/wx/opts.cpp

Prevents crash when an invalid or a non existing api is used in
vbam.conf

Revert to a default audio api (SDL) when config is invalid

---

src/gb/GB.cpp
src/libretro/libretro.cpp

This uses full size of gbWram[] so we have a continouos memory block
for RAM addresses $C000 and $D000 in CGB mode. This helps with
retroachievements.

libretro: Use gbWram[] for $C000 in CGB mode

---

src/gba/GBA-arm.cpp
src/gba/GBA-thumb.cpp

- Resolve some negative **runtime error: left shift of negative value** when running using ASAN in some thumb and arm opcodes
- turned **thumb conditional branches** in macro (its basically the same code, just with different condition to test with). Might need double-check on this (does COND correctly checks if its true or false?), although i already completed about 2-3 playhtroughs of Summon Nights where these issues originally showed.

GBA: Resolve shifting negative value issue in some thumb/arm opcodes

---

src/gba/EEprom.cpp
src/gba/Flash.cpp
src/gba/GBA.cpp
src/gba/GBA.h
src/gba/bios.cpp
src/gba/elf.cpp
src/libretro/libretro.cpp

- use labels instead of magic number for known sizes for pointers and save types
feel free to change any labels or if its better to use #define or const <variable type>

GBA: Remove some magic numbers for main pointers and save types size

---

src/gba/elf.cpp

It reads data from uninitialized memory, converts it to pointer and accesses invalid address 0xCDCDCDCD
[screenshot1](https://imgur.com/a/5vhUOom)
[screenshot2](https://imgur.com/a/UPg77Yl)

bugfix: crash when loading elf

---

src/wx/gfxviewers.cpp

...caused by invalid start address of mapbase.
Fix https://github.com/visualboyadvance-m/visualboyadvance-m/issues/372
Feel free to correct if necessary, since im unfamiliar with wx.

Map Viewer: Fix crash when running  a gb/gbc game,

---

src/common/ConfigManager.cpp
src/wx/wxvbam.cpp

We check if `$HOME/.vbam` exists; if it does, then we use
`$HOME/.vbam/vbam.conf`; otherwise, use
`${XDG_CONFIG_HOME:-$HOME/.config}/visualboyadvance-m/vbam.conf`.
Fix for #94.
@rkitover Here it is a first code for this. I have some comments to do about it, so we could check for improvements:
1. I see the config file is `vbam.ini` (first try) or `vbam.cfg` for Windows and MacOS, but the name for Linux is `vbam.conf`. I kept this, since this is what we discussed previously, but maybe we could use the name for Win and Mac with Linux for the XDG Dir. I am not sure how hard this is right now, but with wxWidgets >= 3.1 it should be a piece of cake. 
2. I believe we could also use the time until wxWidgets >= 3.1 became stable as a "adaptation time" for users on Linux. I mean like only using the …

[WIP] Add support for the XDG Base Dir Spec for Linux with legacy support.

---

src/Util.cpp
src/Util.h
src/common/ConfigManager.cpp
src/common/ConfigManager.h
src/sdl/SDL.cpp
src/wx/wxvbam.cpp

@rkitover 
As we previously discussed, these were the next steps to support the spec. So keep This includes:
***What was done***
1. Fix `#ifdef` to support more platforms for the spec.
2. Changing dirs from `DOT_DIR` `.vbam` to a XDG Dir 
`${XDG_DATA_HOME:-~/.local/share}/visualboyadvance-m`. This is for the SDL port and it is mainly for Unix.
3. Migration. From `vbam.conf` to `vbam.ini` automatically. This includes a appropriate error message from `wxWidgets`.
***Testing***
1. As discussed #94.
2. Also more tested by me manually. I build the SDL port, run a game and try to save the different types of files and see if theu go into the XDG dir.
3. Manual testing. There are 4 cases: (1) `vbam.ini` exists and `vbam.conf` doesn't; (2) `vbam.ini` and `vbam.conf` exist; (3) neither file exist; …

[WIP] XDG Base Dir Spec followup.

---

src/wx/wxvbam.cpp
src/wx/wxvbam.h

@rkitover 
I think I found the error for the `segmentation fault` on Linux.
The function `bool wxvbamApp::OnCmdLineParsed(wxCmdLineParser& cl)` on `wxvbam.cpp` has this
scope at its end:
```
home = strdup(wxString(wxApp::argv[0]).char_str());
SetHome(home);
LoadConfig(); // Parse command line arguments (overrides ini)
ReadOpts(argc, (char**)argv);
```
On the other hand, this function returns `false` before this when you use the command line
with any option (`--help`, `--print-cfg-path` etc). The variable `home` is declared
as a private variable `char *` on `wxvbam.h`.
On the destructor in `wxvbam.h`, we have
```
wxvbamApp::~wxvbamApp() {
free(home);
}
```
This variable is supposed to be initialized with the `strdup`, but it does not
reach the code with any command line param. This is the …

Fix segmentation fault issue when using WX port command line on Linux and MacOS.

---

src/Util.cpp
src/Util.h
src/common/ConfigManager.cpp
src/wx/wxvbam.cpp

@rkitover This is a little bit of cleanup. On #94 we discussed about managing a single config file for all platforms (`vbam.ini`), so we needed to also include a migration path for `vbam.cfg` on MacOS and Windows.
We also had some stuff duplicated the `FILE_SEP`, like `${XDG_CONFIG_HOME}//visualboyadvance-m` from the xdg functions. Although it has no problem, since all platforms understand the duplicate `FILE_SEP`, it was a quick fix, so why not?
Finally, it is always a good practice to set a pointer to NULL after deallocating it.  This was missing from the variable `home` that was the cause of that segfault command line issue.

Overall cleanup.

---

src/wx/wxvbam.cpp
src/wx/wxvbam.h

@rkitover I have an idea about how we could handle the return code `255`. But first, I will tell what I think it is happening, so you can check if we are on the same page.
When we run 
`./visualboyadvance-m --help; echo $?`
or 
`./visualboyadvance-m --print-cfg-path; echo $?`
we get the value `255`, which is a non-zero error code. For these 2 cases, we wish we got `0`, since it means the app ran successfully (only printing the asked info and then exiting).
According to my researches, the reason why we get `255` is because we returned `false` on the `OnInit()` function, causing it to exit the program immediately, but in the sense of failing to initialize. Sources [(1)](https://stackoverflow.com/questions/19255020/how-do-i-quit-a-wxwidget-application-when-no-window-was-opened) and …

[WIP] Return non-error code for given command line parameters.

---

src/sdl/SDL.cpp
src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

@rkitover This is another followup work I had to do after #94. There was some stuff bugging me at that time, like whatever option to save file I had on GUI (screenshot, recording etc) was having the default option the same path from the configuration file, where `vbam.conf` was. 
This is not an issue for Windows and MacOS, but for Linux the appropriate path would be the `$XDG_DATA_HOME/visualboyadvance-m`, hence what I am doing here.
Another thing that I had to do was to sync these location with the ones from the SDL port. I am 99% sure that these type of `else` (example) were unreachable:
```
if (batteryDir)
...
else if (homeDir)
...
else // <- useless, it would never reach here
```
Now, all these locations are synced with the ones from the WX. The order is:
1. StateDir / BatteryDir / …

XDG followup work.

---

src/wx/wxvbam.cpp
src/wx/wxvbam.h

@rkitover I believe this fixes the sanity check problems that we are having. I did some quick testing here, and I think that at least with `xvfb-run` it should work. Also, this includes returning code `0` for wrong params, like we discussed in #388.
If you can, try to test this before merging as well. Here I tried to solve the delay when running `--help`. There is an even quicker way, but requires some more dancing in the code. I will try to bring a solution. It move this code to the very top of the `OnInit`:
```
if (!wxApp::OnInit())
return false;
if (console_mode)
return true;
```
Check if you like it.

Fix problems of command line parameters.

---

src/wx/panel.cpp

@rkitover The window was being forced to resize every time a game loads. The idea is to resize only if the minimum size (determined by the zoom configuration) requires a window bigger than the custom one set by the user. In this case, we should set it to the minimum size asked by the zoom.
@retro-wertz I believe this should be enough to deal with the zoom. If I understand it right, the zoom level X means the minimum size for the window is `X * (min_width, min_height)`. Is this correct?
There is still something bothering me here. The window size set by the frame does not include status bar or menu bar. There might be some cases where the window will be either a little bigger than expected (the status bar pixels) or be slight incorrect `X,Y` starting positions. I will try some more tests to …

Fix for resizing window geometry when loading games.

---

src/filters/2xSaI.cpp
src/filters/hq/c/hq_shared.h
src/gb/GB.cpp
src/gb/gb.h
src/gb/gbSGB.cpp
src/gb/gbSound.cpp
src/gba/GBA-arm.cpp
src/gba/GBA-thumb.cpp
src/gba/debugger-expr-lex.cpp
src/gba/remote.cpp
src/sdl/expr-lex.cpp
src/sdl/getopt.c
src/wx/opts.cpp

@rkitover The work we needed to do after #396. I need some checks here.
Some of these files do not include any headers except local ones. That is the reason why I copy & paste the solution for many files. I know there were memory leaks issues, but they came after compilation warnings so I think we can put these two together here.

Fix compilation warnings for MacOS build.

---

src/wx/panel.cpp
src/wx/wxvbam.cpp

@rkitover @retro-wertz This is a little trick because we need to decide a behaviour.
The reason such thing happened was  with option `Display/Stretch=1`. Changing on file `panel.cpp`:
```
GetSizer()->Add(w,    frame_priority, gopts.retain_aspect ? (wxSHAPED | wxALIGN_CENTER_HORIZONTAL | wxEXPAND) : wxEXPAND);
to
GetSizer()->Add(w,    frame_priority, gopts.retain_aspect ? (wxALIGN_CENTER_HORIZONTAL | wxEXPAND) : wxEXPAND);
```
The `wxSHAPED` is behind this. From the docs: `wxSHAPED flag tells the window to change it is size proportionally, preserving original aspect ratio`. When we had a default startup, the zoom level decided the window size (by setting the minimal one required for it). Then you could expand however you like it and it would work. When trying a custom size, the window …

Fix incorrect starting video showing and geometry.

---

src/wx/panel.cpp

@rkitover I copied my commit message here. See if you can understand.
```
Fix continuous sprinting when using a modifier key as a mapping key (#142).
When holding a key(W,A,S,D) and then pressing a modifier(SHIFT,CTRL,ALT), we get two sets {MOD,MOD,0} and {KEY,MOD,0} with MOD > 0 after a {KEY,0,0}. When releasing the initial key while holding the modifier, we search for {KEY,MOD,0} instead of {KEY,0,0} to be removed.
Finally, when releasing the modifier, we remove {MOD,MOD,0} from our stack. This means the {KEY,0,0} stays "pressed", although no input is being taken from the keyboard.
Full example using WASD as movement keys and L_SHIFT as our B button.
1. Press and hold "A" --> add {A,0,0} to stack;
2. Press "L_SHIFT" --> add {L_SHIFT,4,0} and {A,4,0} to stack;
3. Release "A" --> remove …
```

Fix #142 and #390.

---

src/common/ConfigManager.cpp
src/wx/opts.cpp

We have some possibilities here. This warning is issued because "GBA/LinkHost" is an empty string unless the user knows he needs to set a server ip address for whatever he wants to do.
The current code for this shows we use the `gopts.link_host` everywhere:
```
$ fgrep -RnwI . -e "link_host"
./src/wx/guiinit.cpp:93:            bool valid = SetLinkServerHost(gopts.link_host.utf8_str());
./src/wx/guiinit.cpp:119:            connmsg.Printf(_("Connecting to %s\n"), gopts.link_host.c_str());
./src/wx/guiinit.cpp:3094:            gettc("ServerIP", gopts.link_host);
./src/wx/guiinit.cpp:3836:        bool isv = !gopts.link_host.empty();
./src/wx/guiinit.cpp:3839:            isv = SetLinkServerHost(gopts.link_host.utf8_str());
./src/wx/opts.cpp:206:    STROPT("GBA/LinkHost", "", …
```

[WIP] Fix "Joybus host invalid; disabling" warning.

---

src/Util.cpp
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/wxvbam.h

@rkitover this is a quick fix, considering there still are some possible solutions available.
At first, when this issue first happened, I thought it very strange for something to break like this suddenly. Then I remembered that from `2.1.1.` to `2.1.2` there was that compilation warnings commit. I reviewed what I changed (already considering that as the cause), but failed to find the answer.
So I went to your `unicode-filenames` branch to test some stuff, but the compilation was failing with weird errors (that do not happen for current master). That's why I created this new branch and cherry-picked your commit from there. 
I will comment some of the code, but it should be fairly straightforward about why this works. It is probably not the best solution, though.
As far as testing goes, I …

[WIP] Fix for unicode related issues.

---

src/wx/guiinit.cpp

@rkitover 
We show the wrong description for these shortcuts, although it works
correctly for the keybinding.
Original:
New:
I will explain why this happens on the code. Fix for #411.

Fix key shortcuts for save/load states.

---

src/wx/cmdevents.cpp
src/wx/wxvbam.cpp

We use the same event for both keybinding and `Emulation` > `Pause`
actions. The issue here is that the menu item is checkable, meaning
that you toggle its value and then run the handler.
The handler checks the value of the menu item `Emulation` > `Pause`,
and toggle the game pause accordingly. Such thing does not happen when
using the keybinding. Hence, it did not toggle the pause as expected.
- Related to #454.

Fix pause toggle keybinding when unmuting.

---

src/wx/cmdevents.cpp
src/wx/opts.cpp
src/wx/xrc/MainMenu.xrc

Use a accelerator to quickly provide a way to change to/from multipliers
of the original size.
- Fix #415.
The only thing I would like to add here is some stuff is being done the way it is so we can also allow the users to change these keybindings via `Options` > `Key Shortcuts`. This explains whey this appears on the main menu.

Add hotkeys for changing sizes (1x ... 6x).

---

src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

@rkitover This is a very weird behaviour for this output module. When I checked #65, I got several types of errors (like first `double free`, then `segfault`, then `free(): corrupted unsorted chunks`). With the help of @retro-wertz, we used ASAN to find a specific line on our code, just before the error's party begun.
I will point out the code, hoping you can have a better understanding about this.

[WIP] Fix load state failing to load with Simple output module.

---

src/wx/widgets/joyedit.cpp

@rkitover  I had to fix some spelling for the french translation and create a function to initialize the regex properly. If we try like was before, the regex compiles the english words (don't use gettext to translate it). This is why the configuration was not set.
I have to update the transifex too, but first want your feedback regarding this. I suggest we drop all translation for buttons/axes/joy and use the english text only. The labels will remain translated, but these may cause a minor inconvenience when switching languages, as the app will complain about weird strings (set as french, then use en_US ==> warning about wrong configuration).
Fix #441, #437 and #273. I tested for french, german and portuguese. Everything worked as expected.
After your feedback I will update transifex …

Translation issues.

---

src/common/ConfigManager.cpp
src/sdl/SDL.cpp

@rkitover This is a followup work for 684b1bb7aaa220b8f00b46612846fb04c0f5fe89. I checked on the code if that variable `homeDir` was being used elsewhere, and turns out it was unnecessary.
We also did not free that `strdup`. So there was a small memory leak. This should allow us to not worry about this anymore.

Fix some memory leak.

---

src/wx/wxvbam.cpp

If the user pauses with the keybinding or the menu `Emulation` > `Pause`
while `Pause when inactive` is enabled, the game should not unpause when
the window receives focus again. It should wait for the user to trigger
the manual unpause.
- Fix #460.

Fix pause behaviour with `Pause when inactive`.

---

src/sdl/SDL.cpp

@rkitover We were trying to set options before loading the configuration file given by `--config`. Hence, the default config was being used and, when we loaded it, we did not set some SDL port options, like controller input keymap.
Fix #469.

Use --config option to load configuration file.

---

src/wx/sys.cpp

@rkitover This is a regression needed for #476 (it will not close it, but partially fix it).
I also did the test of `log("%02x %04x %08x\n", 0xff, 0xffff, 0xffffffff);` on a random scope to check its return and it seems to be working.
The memory leak is a bit more complicated... There are some things mixed there and It is probably needed to do something more towards refactoring. It will be on the list of memory issues, nevertheless.

Fix wxWidgets assertion error on `Logging...` menu.

---

src/wx/opts.cpp

@rkitover This should solve #463. If the key does not exist on `vbam.ini`, we set our default keybinding for that key. If the key is empty (for whatever reason), we keep the way it is: empty. It deals with case 2 from the issue.
I wanted to check if we could handle the case where a default key is set to something else and the key does not exist, but I think this is not necessary. This is a very weird use case, and I believe users would set the key to empty instead of removing it from the configuration file.

Set default keybinding when key does not exist.

---

CMakeLists.txt
src/common/ffmpeg.cpp
src/common/ffmpeg.h
src/gb/GB.cpp
src/wx/cmdevents.cpp
src/wx/panel.cpp
src/wx/wxvbam.h

@rkitover @ZachBacon 
```
We create a namespace to deal with most of our recording solution.
Besides that, we also add some functions to remove the need of
including libavutil headers on other part of the code. This is meant to
isolate most of recording solution components on the proper files.
We will start with a limited number of codecs supported; slowly we
should add them as they are tested (the previous one did not work for
most codecs listed).
This should support `ffmpeg 4.1` and further, including removing
all compilation warnings related to versions discrepancy.
```
This is my promised solution for #124, and it includes a heavy refactoring from the former one. I tried to put as much work as possible on this (not because it is hard, but I needed a continuous amount of time to do it; …

[WIP] Fix video/audio recording.

---

src/wx/viewsupt.cpp

@rkitover This is like one of those dumb segfaults that I mentioned earlier. As soon as you click this item, it appears a wxWidgets error message. It has been like this since my pr to remove most of the compilation warnings... 
@retro-wertz You are interested on this, at least at the time of the issue reporting. Check if this is what you want and test it, please. I know I can see rows of memory maps, but I don't know if they are correct or not. The GUI behaviour I could test myself, but we need to be sure that I am not going to break something else with this solution.
Feel free to comment whatever you want. If there is some type of improvement desired, leave a note. I will be off from now until next wednesday (14.8.19) to focus on personal stuff. When I am back, I will see what I can do …

Fix behaviour of `Tools` > `Memory Viewer`.

---

src/wx/panel.cpp

From my very superficial understanding, the `rom[]` resize happens only when `rom_size` is greater than `0x2000000`.
We should probably study this better for an actual explanation.
- Fix #487.
This is a little shady for me... As I don't quite understand what is the problem of resizing `rom[]`. This solution is very simple, though. It should still protect the case for when the resize could happen. This is only for GBA ROMs, it seems (because they are bigger, probably);

Allow UPS patch for GBA games.

---

CMakeLists.txt
src/filters/xBRZ/xbrz.cpp
src/filters/xBRZ/xbrz.h
src/filters/xBRZ/xbrz_config.h
src/filters/xBRZ/xbrz_tools.h
src/filters/xbrzfilter.cpp
src/wx/panel.cpp

@rkitover 
```
Get files from here `https://sourceforge.net/projects/xbrz/files/xBRZ/`.
Then, update the src to handle pitch params. For our case, the pitch
is necessary because we deal with borders (top and right) of our source
image. Normally, we would want to scale without it, and therefore we
need to adjust the pointers to skip the borders.
If we have a `width + 1 pixel border` per line, the we need to scale
a image with `width` line size, but advancing the pointer for each new
line processed including the border on the count.
Also, since our output pointer also allocates for the border, we need
to adjust the output moving pointer for each line in a custom way.
(output border in this case)
- Fix #164.
```
The best way to review this is to get the source code from the latest xBRZ and …

Update to xBRZ `1.7`.

---

CMakeLists.txt

```
We check if the compiler has asan support when the option is enabled.
If it does not, then we stop compiling with the proper message.
To test this, we use `gcc (GCC) 4.4.7` (no asan support) and
`gcc (GCC) 9.1.0` (asan is supported). Call cmake like this:
`cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=On` and
`CXX=g++-4.4 cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=On`
we then check that it fails for the older version and it works for
the newer gcc, like expected.
- Fix #409.
```
@rkitover  I know this PR has weird timing, but I try to match whatever tool I am handling at work with the closest thing we have here. This way I can double practice whenever I have to do stuff. Check if this is enough.

Check ASAN support when `ENABLE_ASAN=ON`.

---

CMakeLists.txt
src/common/ConfigManager.cpp
src/gba/agbprint.cpp
src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/wxvbam.h
src/wx/xrc/MainMenu.xrc

```
We protect all code relevant to disabling this property with either
`BKPT_SUPPORT` or `NO_DEBUGGER`. This is mostly debugging options or
prints scattered around the code.
We also adjust cmake to ignore the specific files surround it, but
allowing the rest of the GUI to work.
- Fix #431.
```
@rkitover  This should work for the compilation. The only decision missing is to know if we prefer to remove the GDB stuff from the menu, or just grey it out. The current solution removes it from the menu, but there is also code scope for the other solution.
The `agbprint` stuff is also a question mark for me, since it uses debugging functions but I have no idea about what it is used for. We need to understand it to know what to do.

Fix compilation issue when `ENABLE_DEBUGGER=Off`.

---

src/filters/xBRZ/xbrz.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/sys.cpp
src/wx/xrc/MainMenu.xrc

@rkitover These are some leftovers from a couple of issues.
ebe1be7: Some UTF-8 messages were being displayed wrong.
387a1c8: the `xBRZ` optimization for some platforms. The only one missing from what I wanted is the `Windows x64` because it does not accept inline ASM. It is too much work to make it worth for visual studio.
a6f5848: I am studying `WinSparkle` for a definitive solution. So, although it fixes the crash, I will let the issue open for now.
4998a5d: From
to

Leftovers.

---

src/wx/wxvbam.cpp

```
All keys were being captured before being processed by any window of the
app to check for accelerators. This meant being impossible to use any
keys for input if they were saved for an accel.
- Fix #516.
```
Sorry about this. This slip through because my custom desktop settings.

Fix key accel overriding menus and dialogs.

---

CMakeLists.txt
cmake/HostCompile.cmake
cmake/PathRun.cmake
fex/CMakeLists.txt
src/gcc-wrap.c.in

For more details please see `cmake --help-policy CMP0058`. I tested this with both `cmake -GNinja ..` using `samu` and with `gmake`.
```
CMake Warning (dev):
Policy CMP0058 is not set: Ninja requires custom command byproducts to be
explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
This project specifies custom command DEPENDS on files in the build tree
that are not specified as the OUTPUT or BYPRODUCTS of any
add_custom_command or add_custom_target:
bin2c
For compatibility with versions of CMake that did not have the BYPRODUCTS
option, CMake is generating phony rules for such files to convince 'ninja'
to build.
Project authors should add the missing BYPRODUCTS or OUTPUT options to the
custom commands …
```

cmake: Silence cmake policy warning CMP0058.

---

cmake/HostCompile.cmake
src/wx/CMakeLists.txt

This is potential clean up, lets see what CI says. It works here on linux at least.

cmake: Use add_executable when not cross-compiling.

---

.travis.yml

This tests clang builds on trusty for both standalone and libretro.
The caveat is that that this shows many warnings with standalone which could be something wrong with travis's cmake or clang?
```
[  0%] Building C object src/wx/CMakeFiles/bin2c.dir/bin2c.c.o
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/visualboyadvance-m/visualboyadvance-m/build' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /home/travis/build/visualboyadvance-m/visualboyadvance-m/fex' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /usr/include/SDL2' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-I /usr/include/AL' [-Wunused-command-line-argument] …
```

travis: Test clang builds.

---

.travis.yml
CMakeLists.txt
src/wx/CMakeLists.txt

This tests `make install` with travis everywhere except libretro to better catch issues.
The second commit uses a modern install target for `visualboyadvance-m` to fix `make install` on osx. I am not sure useful this is on osx, but it seems like an easy fix regardless. Considering what to do with `make install` better on osx can be done later.

travis: Test make install.

---

src/wx/CMakeLists.txt

On the `mingw` travis builds it will install `visualboyadvance-m` twice.
```
-- Installing: /tmp/VBAM/home/travis/build/visualboyadvance-m/visualboyadvance-m/build/visualboyadvance-m.exe
-- Installing: /tmp/VBAM/usr/lib/mxe/usr/x86_64-w64-mingw32.static/bin/visualboyadvance-m.exe
```
This will make it so that only the second instance is installed.
```
-- Installing: /tmp/VBAM/usr/lib/mxe/usr/x86_64-w64-mingw32.static/bin/visualboyadvance-m.exe
```
I am not sure there is a good reason why its being installed twice or not and am opening this PR for review.
I also removed the unused `WX_EXE_NAME` variable.

cmake: Don't install visualboyadvance-m twice on WIN32.

---

.travis.yml

Seems adding `-a` to `xvfb-run` allows it to work on xenial and bionic.
Reference: https://github.com/travis-ci/travis-ci/issues/4387

travis: Test xvfb on xenial and bionic.

---

CMakeLists.txt

Silences many noisy warnings with debug builds.
```
[79/196] Building CXX object fex/CMakeFiles/fex.dir/fex/Zlib_Inflater.cpp.o
In file included from ../fex/fex/Zlib_Inflater.cpp:3:
In file included from ../fex/fex/Zlib_Inflater.h:7:
In file included from ../fex/fex/Data_Reader.h:7:
In file included from ../fex/fex/blargg_common.h:8:
In file included from /usr/include/assert.h:35:
/usr/include/features.h:382:4: warning: _FORTIFY_SOURCE requires compiling with optimization (-O) [-W#warnings]
^
1 warning generated.
```

cmake: Silence _FORTIFY_SOURCE warnings with debug builds.

---

src/wx/viewers.cpp
src/wx/viewsupt.cpp
src/wx/viewsupt.h
src/wx/widgets/wx/sdljoy.h
src/wx/wxvbam.h

The `AcceptsFocus`, `Clone` and `HasFocus` functions seem unused and can be removed. While `Show` is renamed to `ShowAddr` to not conflict with unrelated functions.
@rkitover Please take a look at this closer to make sure I am not doing anything stupid. I'm not that great with C++.
```
[187/196] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/viewsupt.cpp.o
In file included from ../src/wx/viewsupt.cpp:1:
../src/wx/viewsupt.h:197:10: warning: 'Viewers::MemView::Show' hides overloaded virtual function [-Woverloaded-virtual]
void Show(uint32_t addr, bool force_update = false);
^
/usr/include/wx-3.0/wx/gtk/window.h:64:18: note: hidden overloaded virtual function 'wxWindow::Show' declared here: different number of parameters (1 vs 2)
virtual bool Show( bool show = true );
^
In …
```

wx: Silence -Woverloaded-virtual warnings with debug builds.

---

src/wx/wxvbam.h

This tries to fix an unconditional jump or move on an uninitialized value as show by valgrind when running `--help`.
My understanding is that `overrides` is only set when `console_mode` is false and should only be deleted when `console_mode` is false where it was being deleted regardless before. At least this makes valgrind happy and it seems to work correctly here.
Please review this to make sure I understood this correctly and have the right solution.
```
$ valgrind ./visualboyadvance-m --help
==15788== Memcheck, a memory error detector
==15788== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15788== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==15788== Command: ./visualboyadvance-m --help
==15788== 
VisualBoyAdvance-M
Usage: visualboyadvance-m …
```

wx: Fix conditional jump on uninitialized value with valgrind.

---

.travis.yml

It seems the crashes with `--help` were fixed in commit https://github.com/visualboyadvance-m/visualboyadvance-m/commit/65c908141c46156cfd573a4e57cf9ac70c55c2d3 and I forced the rebuilds in travis for the mac build 5 times. We should let it pass travis pass one more time to be sure.

travis: Test --help on osx.

---

.travis.yml

The end of standard support for trusty ended in April 2019 and the end of life is April 2022. For xenial the end of standard support is April 2021 and the end of life is April 2024.
Most users should have xenial or newer at this point.
Source: https://wiki.ubuntu.com/Releases
It seems the crashes with `--help` were fixed in commit https://github.com/visualboyadvance-m/visualboyadvance-m/commit/65c908141c46156cfd573a4e57cf9ac70c55c2d3 and I forced the rebuilds in travis for all of the ubuntu builds 5 times each. We should let travis pass one more time to be sure.
For trusty I would suggest leaving one build until one of the following happens.
* It becomes too hard to maintain.
* The EOL is reached in April 2022.
* Travis removes their support.

travis: Make xenial the main distribution.

---

installdeps

```
Try to guess the correct mxe apt package repository based on
`lsb_release` codename.
```
I did test this it worked perfectly for `ubuntu cosmic`. Now it compiles out of the box. We can safely merge this. Sorry about the delay!

installdeps: detect correct mxe apt repo

---

src/wx/panel.cpp

```
We don't want to display the top border when using filters, since it
is a single line with black pixels.
- Fix #561.
```
This was tested with the game `Marie, Elie & Anis no Atelier - Soyokaze kara no Dengon`.

Remove top border black line when using filters.

---

.gitignore
po/wxvbam/wxvbam.pot
src/common/SoundSDL.cpp
src/common/contains.h
src/common/range.hpp
src/wx/CMakeLists.txt
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/widgets/sdljoy.cpp
src/wx/widgets/wx/sdljoy.h
src/wx/wxlogdebug.h
src/wx/wxvbam.h

Use the SDL GameController API with SDL events instead of polling
manually. Run SDL_PollEvent() in the panel OnIdle().
The API to the GUI remains the same, the sending of wxSDLJoyEvent
events. Except there are no more hat events, we just use the
GameController buttons. Also the GUI now has to make arrangements for
wxSDLJoy::Poll() to be called periodically, for the config dialog this
is done with a timer.
All Xbox 360 controller buttons and axes are now in the defaults, and
the SDL GameController API will map them to the appropriate keys on
other controllers.
As a consequence of using SDL events, controller attach/detach from the
system is now also handled correctly. It is no longer necessary to have
the controller attached and turned on when the program launches.
Signed-off-by: Rafael …

Joystick handling refactor.

---

src/common/Patch.cpp
src/gba/GBA.cpp
src/gba/GBA.h
src/sdl/SDL.cpp
src/wx/panel.cpp

Fix https://github.com/visualboyadvance-m/visualboyadvance-m/issues/549
- Add support for BPS patch format (Artiip)
- Fix crash when new size is larger than rom size after patching. This was caused because the rom block in memory is now less than required afte the realloc(). Reallocating the memory block back to the required size of 0x2000000 fixes this.

Add BPS patching support (Artiip) and fix

---

src/gba/Cheats.cpp

Although a length check is being performed on the imported GSA Codes file [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gba/Cheats.cpp#L2082), `len` is both a signed `int` and attacker controlled.
With a specially crafted GSA Codes file, an attacker could specify a value for `len` that overflows the `int` type, rolling over into a negative number. By doing so, the attacker can bypass the conditional mentioned above.
(highlighted bytes used for len)
(the JLE signed conditional instruction is being used, our len of 0xFFFFFFFF will be interpreted as -1)
The `fread` [length parameter](http://www.cplusplus.com/reference/cstdio/fread/) is of type `size_t` which is an `unsigned int`, this will result in `len` being interpreted as a large `unsigned int`, allowing …

Fix integer overflow in cheatsImportGSACodeFile.

---

src/common/Patch.cpp
src/common/ffmpeg.cpp
src/wx/cmdevents.cpp

@rkitover I changed the default audio recording to `.wav`. Is there a reason why when you select the file type on the wxWidgets window, it does not change the filename to its current extension?
If I select `mp3`, I want to not only show the `*.mp3` files on the current dir, but also toggle the `game.wav` to `game.mp3` on the filename.
I want to include a possible fix for this here, so if there is none, I will merge this myself.

Some leftovers.

---

po/wxvbam/wxvbam.pot
src/gba/GBA.cpp
src/gba/GBA.h
src/gba/ereader.cpp
src/wx/cmdevents.cpp
src/wx/xrc/MainMenu.xrc

This PR fix a issue with loading e-Reader dot code.
Specifically, it is as follows.
- Even if Dot code file is not specified, it tries to read as eternal and does not accept button input.
- In Japanese etc., the path of Dot code file is garbled internally.

Fix: a issue with loading e-Reader dot code

---

CMakeLists.txt
headers/stb/stb_image.h
headers/stb/stb_image_write.h
src/Util.cpp
src/wx/sys.cpp

@rkitover This one is the work following this [comment](https://github.com/visualboyadvance-m/visualboyadvance-m/pull/614#discussion_r381165263). There is probably more to do, to fully remove it, but I want to start here.
Tested with Pokemon Crystal prints, from the pokedex screen. It at least does what last version did (`2.1.4`).

Replace libpng with stb_image.

---

src/wx/panel.cpp

@rkitover Would you mind testing this solution for vsync? It worked on my linux (nvidia proprietary) and `Windows 10` (optimus).
I have a notebook with intel HD graphics. As soon as I finish installing Linux, I will test this there too.
I am not interested yet on changing the structure of our output module classes. I will be reviewing that soon, but I would prefer to start from zero. If you agree, I will delete the `vsync` branch.
```
The vsync has to be {dis,en}abled before a ROM is loaded or we need to
restart the output module to apply it.
We also support MESA based installations (Intel HD Graphics, AMD/ATI and
Nouveau) on Linux.
```

Use proper functions and checks for OpenGL VSYNC.

---

CMakeLists.txt
src/gba/GBALink.cpp
src/gba/GBALink.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h

Allow binding specific server IP.
For the netlink dialog, leave the server IP text field enabled when the
server radio button is selected and bind it to the new option
gopts.server_ip which defaults to "*" for binding on all addresses,
which was the previous behavior.
Copy this value to the new GBALink global IP_LINK_BIND_ADDRESS and use
it when creating a listening socket.
SFML supports creating sf:IpAddress values from hostnames, consequently
no additional code is needed to support hostnames in the netlink dialog.
Change GetLinkServerHost to return the primary local address when the
value is "*", which was the previous behavior, and the set value
otherwise.
Remove the min/max macros from GBALink as they are unnecessary and
conflict with std headers.
Require at least SFML 2.4 instead of …

Allow binding specific server IP.

---

src/System.h
src/common/ConfigManager.cpp
src/common/ConfigManager.h
src/gb/GB.cpp
src/gba/GBA.cpp
src/libretro/libretro.cpp
src/sdl/SDL.cpp
src/wx/cmdevents.cpp
src/wx/gfxviewers.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/viewsupt.cpp
src/wx/wxvbam.cpp
src/wx/xrc/GBOAMViewer.xrc
src/wx/xrc/GBTileViewer.xrc
src/wx/xrc/MainMenu.xrc
src/wx/xrc/OAMViewer.xrc
src/wx/xrc/TileViewer.xrc

@rkitover I think I found a way to solve the modal issue for Windows. Check it out.
I am going to do a double check on all of this, but I also ask for your help to test it and review the overall design of the changes (especially the modal solution).
I have a slight suspicion about some of our debugging functions, but I have to go on a little more before making it work. I should be able to give some feedback this weekend.
While working on this, I had a light about our current throttle issues. Try using the `2.1.1` version and see if you can actually have a speedup.
There is an LCD mode filter for GBA that I made work like a toggle. So you have to enable or disable it. I really like to give the user this type of power, although someone will probably complain...
I will update this comment …

Various Fixes

---

po/wxvbam/wxvbam.pot
src/common/ConfigManager.cpp
src/common/ConfigManager.h
src/gb/GB.cpp
src/gba/GBA.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/xrc/GeneralConfig.xrc
src/wx/xrc/SpeedupConfig.xrc

In the Speedup/Turbo config panel, make frameskip the first choice,
followed by throttle, and add a warning that throttle may not work due
to vsync.
Fix throttle=0 (unlimited speed) settings for both the Speedup/Turbo
config panel and the general throttle setting and make 100 the default.

Speedup/Turbo/Throttle fixes.

---

src/System.h
src/Util.cpp
src/Util.h
src/common/ConfigManager.cpp
src/common/Patch.cpp
src/common/Patch.h
src/gb/GB.cpp
src/gb/gbCheats.cpp
src/gba/Cheats.cpp
src/gba/GBA.cpp
src/gba/ereader.cpp
src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/wxhead.h
src/wx/wxvbam.cpp

@rkitover The issue #625 was more complicated than just the BIOS not loading. When I started playing with files on Windows, I was only being able to load the game (zip) and BIOS. Not battery, save states, or any other file associated with my games.
I tracked what was happening with the BIOS: 
```
./src/gba/GBA.cpp: void CPUInit(const char* biosFileName, bool useBiosFile)  ==> utilLoad(biosFileName, CPUIsGBABios, bios, size)
./src/Util.cpp: uint8_t *utilLoad(const char *file, bool (*accept)(const char *), uint8_t *data, int &size) ==> fex_t *fe = scan_arc(file_conv, accept, buffer);
./src/Util.cpp: static fex_t *scan_arc(const char *file, bool (*accept)(const char *), char (&buffer)[2048]) ==> fex_err_t err = fex_open(&fe, file);
./fex/fex/fex.h:80:fex_err_t fex_open(fex_t **out, const …
```

[Windows] UTF8

---

src/gb/gbMemory.cpp

MBC30 is a variant of MBC3 with a 4MiB ROM size and a larger RAM size.
https://gekkio.fi/files/gb-docs/gbctr.pdf
Allow addressing 4MiB of the ROM in MBC3 ROM bank select if the ROM size
is 4MiB.
Fix provided by roytam1.
- Fix #652.
@roytam1 @FredrIQ @negativeExponent @denisfa 
Please review.

GB: Support 4MiB MBC30 ROM bank select.

---

src/gba/ereader.cpp

reg[0].I is unsigned so checking if it is greater than or equal to zero is always true by definition.
Fixes #578

Removing meaningless conditional

---

src/wx/cmdevents.cpp
src/wx/panel.cpp

When toggling "retain aspect ratio", destroy the drawing panel so it is
recreated with the desired aspect ratio settings.
Only add the vertical spacers when aspect ratio is on, they are not
needed when it's off.
Set the sizer priority of the DrawingPanel to 1 if aspect ratio is off
so that wxEXPAND always works.
Clear the GameArea sizer when attaching a new DrawingPanel, this is so
that the vertical spacers used when aspect ratio is on are not included
when aspect ratio is off.

Fix changing aspect ratio option.

---

po/wxvbam/wxvbam.pot
src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h
src/wx/xrc/MainMenu.xrc
src/wx/xrc/UIConfig.xrc

Add ui/hideMenuBar boolean option, defaulting to on, which hides the
main menubar when the mouse is idle or outside the frame.
This is disabled on mac, because on macs the main menubar is not part of
the application window.
Fix pointer hiding/unhiding by connecting panel events to the gamearea
mouse event handler.
Clean up the pausing when menus are opened code, make it actually work
on Windows.

Hide menubar + minor UI refactor.

---

po/wxvbam/wxvbam.pot
src/wx/widgets/joyedit.cpp
src/wx/widgets/sdljoy.cpp
src/wx/widgets/wx/sdljoy.h

Add support for non-GameController SDL Joysticks.
Add proxy class wxSDLJoyDev to support using either SDL_GameController*
or SDL_Joystick* values in joystate.dev.
Add pretty much identical SDL code to support SDL_Joystick* when the
device cannot be opened as an SDL_GameController*, without changing the
API. SDL_Joystick* devices operate almost identically to SDL_Controller*
devices with their own default mappings, for both events and polling.
Filter axis motion events in the bindings editor widget for subsequent
events within 300ms. This gets rid of the double binding for +1/-1 when
the stick is moved to a direction.

Joystick refactor pt. Deux: Support Joysticks.

---

src/wx/panel.cpp
src/wx/wxvbam.h

Ignore mouse movements of less than 11 pixels, to avoid spurious events
from mice in high DPI mode etc..
- Fix #675.

Decrease mouse sensitivity for menu hiding.

---

src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/wxhead.h
src/wx/wxutil.cpp
src/wx/wxvbam.cpp

@rkitover Now it is correct.
The tests should be:
I decided to write this here so I can remember/document what I tested. Please edit/add if you see something missing.

Input followup

---

src/wx/wxutil.cpp

Followup on baa0341b.
Use ToStdWstring() instead of wc_str() to look up strings in the map,
the key for the map is std::wstring.
I need to add this to the CI.

Fix for non-stl wx builds.

---

src/apu/Multi_Buffer.h
src/gba/Sound.cpp

Stereo buffer is not remade in the case of audio plugin
switch (only affects GBA, not GB).  This results in a crash.
We need to remake the stereo buffer and reinit the pointers
in Gba_Pcm.output or they will be dangling, and lead to a
crash.  Also, cleaning up the Multi_Buffer class a bit.

Addressing audio plugin crash

---

src/wx/widgets/sdljoy.cpp
src/wx/widgets/wx/sdljoy.h

Hopefully fix various bugs caused by not differentiating between SDL
joystick_index and SDL_JoystickID (the joystick instance id.)
Also increase the poll time from 10ms to 25ms.
- Fix #718.
- Fix #726.

Differentiate between SDL joy index/instance_id.

---

src/wx/CMakeLists.txt

I'm not sure what purpose this currently serves but I know that it
breaks the build when CMAKE_PREFIX_PATH is set to something nontrivial. The assignment is sort of nonsensical anyways since `CMAKE_PREFIX_PATH` is a colon-separated list of paths and the `--prefix` option expects just a single one. This predictably does not work if the cmake environment variable has more than one path in it.
Stop doing that.
Let me know if there are steps I can take to test that this doesn't break other distros builds, but it definitely unbreaks mine. For context, I am building with Nix which sets `CMAKE_PREFIX_PATH` to something very long

[rfc] Don't set wx-config prefix from CMAKE_PREFIX_PATH

---

po/wxvbam/wxvbam.pot
src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/widgets/joyedit.cpp
src/wx/widgets/sdljoy.cpp
src/wx/widgets/wx/sdljoy.h
src/wx/wxvbam.cpp

This is a major refactor of the wxSDLJoy class.
* Move handling of SDL objects creation and destruction to its own
class. This simplifies the lifespan of SDL-related objects.
* Re-add handling of HATs. This is necessary for DirectInput
controllers.
* Fix a crash on joystick disconnect.
* Rename the public API for wxSDLJoy to be clearer.
* Add documentation for every class related to wxSDLJoy.
* Change some tabs to white spaces in wxvbam.cpp.

Refactor wxSDLJoy

---

src/gba/GBA.cpp

Some allocators return a non-null pointer when calling *alloc with zero size, that will segfault upon access.
Check for the size parameter before allocating anything to ensure that the breakpoint and trace fields will stay null when `size >> 3` or `size >> 1` is zero.

Handle allocation quirk on non-null-returning allocators

---

src/common/SoundSDL.cpp

I've fixed the bug that causes no audio to play on Windows without a hack, and I've fixed the audio delay. See the commit descriptions for more information.

SDL audio fixes

---

src/sdl/SDL.cpp

Since SDL 2.0.14, KMOD_GUI is no longer a macro but an enum value:
https://hg.libsdl.org/SDL/rev/15a0bc9612e9
So this code broke as the enum value doesn't satisfy `defined()`.
---
Fixes this build issue when using `ENABLE_SDL=ON`:
```
/home/akien/Projects/mageia/Checkout/vbam/BUILD/visualboyadvance-m-2.1.4/src/sdl/SDL.cpp: In function 'void sdlPollEvents()':
/home/akien/Projects/mageia/Checkout/vbam/BUILD/visualboyadvance-m-2.1.4/src/sdl/SDL.cpp:884:45: error: 'KMOD_META' was not declared in this scope; did you mean 'KMOD_ALT'?
884 | #define MOD_NOCTRL (KMOD_SHIFT | KMOD_ALT | KMOD_META)
|                                             ^~~~~~~~~
/home/akien/Projects/mageia/Checkout/vbam/BUILD/visualboyadvance-m-2.1.4/src/sdl/SDL.cpp:1057:46: note: in expansion of macro 'MOD_NOCTRL'
1057 | …
```

SDL: Fix build with SDL 2.0.14 after KMOD_GUI change to enum

---

src/sdl/SDL.cpp

This silences a compiler warning (encountered on GCC 10.2), which complained about `strncpy`'s length parameter being determined by the length of the source string.
I've also fixed some bugged logic on Windows, where the profile path is used instead of the `argv[0]` path because of a shadowed variable. This bug presumably prevents the PATH from ever being searched, and it also seems to have broken the logic for searching the executable directory.

SDL frontend fixes and cleanup

---

src/gba/GBAinline.h

Fixes illegal halfword and byte reads (Croket! 2 slowdown) #804

add a missing break; in half word reads

---

installdeps

I don't know if this is right or not, but I am running an Arch system and tried running `./installdeps` and nothing happened. So I went into the script and figured that it got stuck in the `elif [ -f /etc/os-release ];` block. This file exists on Arch as well, so the block is executed, but arch is not listed in the `case` block, so the script exited without doing anything. And it's only checking for pacman after that, so it never ran `arch_installdeps`.
Don't know if this is the 100% correct fix, but it's working for me now and should also catch cases like that in the future.

Fix Arch installdeps

---

src/wx/wxvbam.cpp

Previously, this function returned -1 or "true" but wxWidgets
defines constants for the returned values for FilterEvent()
overrides so use these instead.

Use constant aliases in MainFrame::FilterEvent()

---

src/gba/Flash.cpp

Erased memory is FFh-filled, not zero-filled.

Fix Flash chip's erase operation

---

src/common/ConfigManager.cpp
src/wx/opts.cpp

This corrects a slight oversight in the opts.cpp and makes the pref reflect the actual setting
fixes #80

Fix autosaveloadcheats and rename pref to autosaveloadcheats

---

CMakeLists.txt
src/wx/panel.cpp

turns out bools are not BOOLS, and PFNWGLSWAPINTERVALEXTPROC is a BOOL
also glGetExtensionsStringEXT expects a Const Char*
Resolves a case of undefined behavior that allows x86 builds to run as fast as x64.

fix x86 builds crashing when /Gs set by Optimizations, turns on full optimizations for x86

---

src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/widgets/joyedit.cpp
src/wx/widgets/sdljoy.cpp
src/wx/widgets/wx/joyedit.h
src/wx/widgets/wx/sdljoy.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

* Add `wxJoystick` to abstract what was previously referred to as
`player_index`. This is a first step towards a larger refactor of
input handling.
* Remove "SDL" from types that are not directly SDL-related, namely
`wxSDLJoyEvent`, `wxSDLControl`.
* Rename `wxSDLJoy` into `wxJoyPoller`. This clarifies the use of this
class.
Issue: #745

Abstract player_index into wxJoystick

---

src/wx/CMakeLists.txt
src/wx/panel.cpp
src/wx/widgets/joyedit.cpp
src/wx/widgets/userinput.cpp
src/wx/widgets/wx/joyedit.h
src/wx/widgets/wx/userinput.h
src/wx/wxutil.cpp
src/wx/wxutil.h
src/wx/wxvbam.cpp

This introduces a new abstraction for any user input. The long-term goal
is to replace every usage of "custom" {key, mod, joy} triplets in the
code base with this new class.
This class implements comparison operators, allowing for faster access
in a set or as a key in a map, compared to the vectors currently used.
Issue: #745

Introduce wxUserInput class

---

po/wxvbam/wxvbam.pot
src/wx/CMakeLists.txt
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/widgets/gamecontrol.cpp
src/wx/widgets/joyedit.cpp
src/wx/widgets/userinput.cpp
src/wx/widgets/wx/gamecontrol.h
src/wx/widgets/wx/joyedit.h
src/wx/widgets/wx/userinput.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This introduces abstractions for a game key (`wxGameKey`), a game
control (`wxGameControl`) and a common global handler for in-game
user input processing (`wxGameControlState`).
User configuration is changed from a vector to a map of `wxGameControl`
to a set of `wxUserInput`, which simplifies input configuration updates.
User input processing for in-game controls is now unified between
keyboard and joypad input, and is much faster in general since access
to game control state is now always logarithmic rather than linear.
This comes at the expense of slightly slower user input configuration
updates. However, in the worst case scenario, this is still done in
O(log(n)).
This removes all uses of `wxJoyKeyBinding`. However, some uses of the
key, mod, joy triplets remain and will be cleaned up …

Refactor game controls bindings

---

src/wx/panel.cpp

Fixes #904 for various Linux distributions including Arch and Ubuntu by defining ```Status``` required by _glext.h_ if it has not already been done.
```
vbam/visualboyadvance-m/src/wx/panel.cpp:2171:
/usr/include/GL/glxext.h:950:9: error: typedef ‘Status’ is initialized (use ‘decltype’ instead)
950 | typedef Status ( *PFNGLXGETTRANSPARENTINDEXSUNPROC) (Display *dpy, Window overlay, Window underlay, unsigned long *pTransparentIndex);
| ^~~~~~
```

error typedef Status fix for #904

---

po/wxvbam/wxvbam.pot
src/wx/autoupdater/wxmsw/autoupdater.cpp
src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/strutils.cpp
src/wx/strutils.h
src/wx/tests/strutils.cpp
src/wx/widgets/gamecontrol.cpp
src/wx/widgets/joyedit.cpp
src/wx/widgets/keyedit.cpp
src/wx/widgets/userinput.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h
src/wx/xrc/DisplayConfig.xrc

This puts the name of the interframe blending algorithm in the OSD instead of the index on activation of the `Change interframe blending` menu entry, as requested by @Squall-Leonhart.
This also sets the default accelerator for this menu entry `CTRL+I`.
I am also doing a minor refactor of my `strutils` library, @Steelskin sanity check please?

Interframe blending changer OSD improvement

---

po/wxvbam/wxvbam.pot
src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/vbam-options-internal.h
src/wx/vbam-options-static.cpp
src/wx/vbam-options.cpp
src/wx/vbam-options.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This change introduces a new class to handle all of the INI options data, VbamOption. A VbamOption represents a single option in the INI file. It is not constructible outside of its implementation, which prevents the initialization of incorrectly formatted options.
Internally, a VbamOption points to a global variable in memory, which holds the value used at runtime. This is because various parts of the codebase edit the global variable rather than going through a central registry. This also means we need to separately update the INI values.
In the future, we may be able to convert all existing reads and writes to the global variable to go through VbamOption. Individual UX elements could link directly to getters/setters for a specific VbamOption rather than have duplicate data.
VbamOption …

[options] Refactor INI options

---

src/common/Port.h
src/gba/GBAinline.h
src/gba/bios.cpp

This adds some helper methods to safely downcast integer types.
Bug: #1003

[build] Fix all warnings in src/gba/bios.cpp

---

CMakeLists.txt
cmake/Set-Toolchain-vcpkg.cmake
cmake/SetCompilerLinkerFlags.cmake
fex/7z_C/CpuArch.c

XAudio2 is disabled because the included header needs to be updated to be parseable by clang.

[build] Add basic clang-cl support

---

src/wx/wxvbam.cpp

A typo in 297d7c06c47015c7da3f98baef11f302cc1206f7 meant main had the wrong prototype on non-Windows systems, breaking the build.

Fix prototype for main

---

po/wxvbam/wxvbam.pot
src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/config/internal/option-internal.cpp
src/wx/config/internal/option-internal.h
src/wx/config/option.cpp
src/wx/config/option.h
src/wx/dialogs/display-config.cpp
src/wx/dialogs/display-config.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/widgets/option-validator.cpp
src/wx/widgets/option-validator.h
src/wx/widgets/render-plugin.cpp
src/wx/widgets/render-plugin.h
src/wx/widgets/wx/wxmisc.h
src/wx/widgets/wxmisc.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This adds a generic Observer interface to config::Option. To demonstrate its intended usage, the Display Configuration dialog and the options it controls have been updated to be entirely handled via the config::Option class.
Implementations for wxValidator are used to validate the flow between the UI and the underlying Option. In turn, modifying the Option value triggers all of its observers that should then do what they need to do.
Rather than explicitly calling all of the needed methods after modifying a global option value, the UI elements that need to be notified when an Option value is modified will be notified via their observers. Runtime assert checks are put in place to prevent infinite recursion if an observer attempts to modify an Option while handling the observer callback. …

[config] Add Observers for Options

---

src/wx/CMakeLists.txt
src/wx/background-input.cpp
src/wx/dialogs/display-config.cpp
src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/wayland.cpp
src/wx/wayland.h
src/wx/wxvbam.cpp

Backport 800d6ed69b from wxWidgets git to fix resizing the `GLDrawingPanel` in Wayland using the EGL `wxGLCanvas`.
Also rename `IsItWayland()` to `IsWayland()`.

Backport 800d6ed69b from wx to fix Wayland EGL pos

---

src/gba/GBA.cpp
src/gba/GBAinline.h
src/gba/bios.cpp

This patch ports over DoDMA from the libretro fork, removes uInt Downcasting on the sine table and changes the bios instructions to signed.
Makes #1020 redundant
Fixes #1050

Correctly port over DoDMA from the Libretro fork and partially revert Downcasting in bios.cpp

---

src/wx/config/option.cpp
src/wx/config/option.h
src/wx/dialogs/display-config.cpp
src/wx/dialogs/display-config.h

The DisplayConfig dialog had a few issues:
* The OK/Cancel buttons were not working as expected. The configuration options would be immediately written whenever some control values were changed. The configuration options are now properly being set on a click to OK, and ignored on a click to Cancel.
* The X button works again.
* There is now proper validation for the Display Scale option, validation ensures that the value is in the right range and incorrect data can no longer be input in that field.
* The Direct3D option is now properly enabled on Direct3D builds.

Fix issues with the DisplayConfig dialog

---

src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/config/internal/option-internal.cpp
src/wx/config/option-id.h
src/wx/dialogs/display-config.cpp
src/wx/dialogs/display-config.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/viewers.cpp
src/wx/widgets/keep-on-top-styler.cpp
src/wx/widgets/keep-on-top-styler.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This also removes limits on the main window position so it can now be negative. This is necessary on Windows where multiple screens to the left and top of the main screen have negative coordinates. A check at startup ensures we always restore the window within the drawable area.

Move display options to owned_opts

---

src/common/ConfigManager.cpp
src/common/ConfigManager.h
src/wx/cmdevents.cpp
src/wx/config/internal/option-internal.cpp
src/wx/config/option-proxy.h
src/wx/guiinit.cpp
src/wx/panel.cpp
src/wx/wxvbam.cpp

This is a preliminary change towards removing ConfigManager from the wx build. Usage of these options has also been modified in the wx frontend.

[ConfigManager] Move wx options to g_owned_opts

---

src/System.h
src/gb/GB.cpp
src/gba/GBA.cpp
src/libretro/libretro.cpp
src/sdl/SDL.cpp
src/wx/sys.cpp

The previously used algorithm was too aggressive. This fixes the issue by using the last second data and using a more gentle adjustment curve to prevent huge changes in frame skipping.

Fix automatic dynamic frame skipping

---

src/gba/Flash.cpp
src/vba-over.ini

This game cart may have a flashcontroller but no flashram onboard, the game automatically goes down the Flash Type path and hits a stackoverflow at cpuSaveGameFunc after cpuSramEnabled returns as false
Avoid this condition by exiting flashSaveDecide when GBA_SAVE_NONE
I have tested a number of titles that create Sram, 512 and 1024Mbit flash and they all still seem to just fine.
Closes #1086

Lets fix Stuart Little 2 properly (maybe?)

---

CMakeLists.txt
src/System.h
src/gb/GB.cpp
src/gb/gbCheats.cpp
src/gb/gbCheats.h
src/gb/gbGfx.cpp
src/gba/Cheats.h
src/gba/GBA-arm.cpp
src/gba/GBA-thumb.cpp
src/gba/GBA.cpp
src/libretro/UtilRetro.cpp
src/libretro/libretro.cpp
src/sdl/ConfigManager.cpp
src/sdl/ConfigManager.h
src/sdl/SDL.cpp
src/sdl/inputSDL.cpp
src/wx/config/internal/option-internal.cpp
src/wx/faudio.cpp
src/wx/guiinit.cpp
src/wx/wxvbam.cpp

This removes ConfigManager from common source and header files and moves it to be only used by the SDL frontend.

Move ConfigManager to SDL

---

src/wx/openal.h

Remove the AL_NO_PROTOTYPES #define, it breaks the build with new versions of OpenAL.

build: fix build with new OpenAL

---

src/wx/CMakeLists.txt

nanosvg is now a required dependency with recent wxWidgets builds.

Add nanosvg library dependency for vcpkg static builds

---

src/common/sizes.h
src/gb/GB.cpp
src/gb/gbCartData.cpp
src/gb/gbGlobals.cpp

This adds asserts for every allocation failure in the core Game Boy emulator. In addition, this replaces some magic values defined constant expressions and removes an unused function.

Sanitize allocations in the Game Boy emulator

---

src/gb/GB.cpp
src/gb/gb.h
src/gb/gbCartData.cpp

* Simplifies most of the GB save/load state code and changes many of the global variable uses to go through gbCartData instead.
* Changes all battery reads to use gzFiles. This seems to have been an oversight in an earlier refactor of the code.
* Removes some unused variables and stops exporting internal-only functions in GB.cpp/gb.h.
Breaking change: Cartridges with no mapper, but a save battery should now properly save and load changes. However, this type of cartridge has not been used in any commercially released software for Game Boy so the exact intended behavior is speculative.

Refactor the save/load state and battery code

---

src/wx/guiinit.cpp

The `wxAcceleratorTable` for the `GameArea` panel was initialized with an array of `wxAcceleratorEntryUnicode`, while the API calls for an array of `wxAcceleratorEntry`. This resulted in the array not being properly interpreted by the `wxAcceleratorEntry`. This fixes the issue by using `wxAcceleratorEntry` to instantiate the array.

Properly initialize wxAcceleratorTable

---

po/wxvbam/wxvbam.pot
src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/config/internal/shortcuts-internal.cpp
src/wx/config/internal/shortcuts-internal.h
src/wx/config/shortcuts.cpp
src/wx/config/shortcuts.h
src/wx/dialogs/accel-config.cpp
src/wx/dialogs/accel-config.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/widgets/user-input-ctrl.cpp
src/wx/widgets/user-input-ctrl.h
src/wx/wxhead.h
src/wx/wxutil.cpp
src/wx/wxutil.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h
src/wx/xrc/AccelConfig.xrc

* Removes wxAcceleratorEntryUnicode and assorted arrays in favor of a new class, `config::Shortcuts`, which handles UserInput assignment to commands and resolution at runtime. `config::Shortcuts` also handles the INI user configuration in a backwards-compatible way. Runtime resolution of UserInput to command is also now logarithmic rather than linear.
* The same shortcut can no longer be assigned to 2 different commands, which fixes #158.
* Moves the `AccelConfig` dialog to its own dedicated class.

Refactor accelerator / global shortcuts handling

---

src/gba/GBA.cpp
src/gba/bios.cpp
src/gba/bios.h

The lz77 uncompresssion software BIOS implementation was exiting early when uncompressing data, if the overall length was larger than advertised in the function parameter. However, real GBA BIOS does read further than the advertised length, so we do here too. This fixes Advance Wars title screen.
This also adds a SoundDriverVSyncOn implementation, silencing an error for some Shrek games, though they still cannot properly boot with an emulated BIOS.
Fixes #789

[bios] Fix lz77 and add BIOS_SndDriverVsyncOn

---

src/wx/cmdevents.cpp
src/wx/wxvbam.cpp

First launch would fail because wx does not create the configuration directory by itself if it does not exist.
This also fixes an incorrect menu option.

Create the config directory at first launch

---

.gitlab-ci.yml
src/libretro/Makefile

Since GameCube, Wii and Wii U are all big-endian systems, we need to call in the Makefile for Libretro cores that these must use big endian code for be able to work, otherwise the emulation will just give a white screen.
Fix by Ploggy, many thanks to him.
Fixes https://github.com/visualboyadvance-m/visualboyadvance-m/issues/1170.

Libretro: Fix GameCube/Wii/Wii U builds. (Ploggy)

---

src/common/sizes.h
src/gba/GBA.cpp

In doMirroring() do nothing if the ROM size is greater than 32MB. This fixes these ROMs automatically working without disabling mirroring in settings.
Fix #1046

Disable mirroring for ROMs > 32MB

---

src/wx/wxvbam.cpp

On initialization, if wxWidgets was compiled without EGL support, check in environment variables if running under Wayland and if so tell GDK to prefer using an X11 backend, causing the program to launch under xwayland.
Fix #1028

Launch on xwayland under Wayland if no EGL

---

src/wx/cmdevents.cpp

Start Network Link is not allowed while Local mode is selected, but state change of Local mode was ignored until an option which triggers EnableNetworkMenu() was selected.
Removed EnableNetworkMenu() from the Configuration option because it doesn't change anything related to Link menu state.

Link: Fix menu not refreshing correctly

---

snapcraft.yaml

Also added the joystick plug, however it doesn't autoconnect. to autoconnect manually you'll need to use snapctl
Permission will be asked by the snapcraft forums to allow it to autoconnect

snapcraft.yml: Rebuilt the snapcraft yaml to utilize core22

---

src/common/ffmpeg.cpp
src/common/ffmpeg.h

This fixes #1214. I also had to make some modifications so that `av_write_trailer()` isn't called during a failure in initialization, as that would cause the program to crash from the potentially-invalid encoder state.

ffmpeg: Use `av_write_trailer()` on stop recording

---

README.md
src/wx/CMakeLists.txt
src/wx/config/internal/option-internal.cpp
src/wx/guiinit.cpp
src/wx/opts.h
src/wx/wxhead.h
src/wx/wxvbam.h

Because of reported framerate issues with the SDL sound driver, remove it and make XAudio2 the default on Windows and OpenAL the default everywhere else.
Rewrite the "sdl" value from users' configs to the new default.
Make OpenAL a mandatory dependency as well.
Fix #709

Remove SDL sound driver

---

installdeps

Change sys-devel to dev-build to match current gentoo package naming convention. Also add --ask flag to prompt for confirmation before merging packages.

build: fix gentoo dependency namespaces

---

CMakeLists.txt
cmake/Options.cmake

This moves all build options to their own file to clean up the main CMakeLists.txt. In addition, this upgrades the minimum required CMake version and changes the build to use CMAKE_MSVC_RUNTIME_LIBRARY rather than hardcoding the MSVC ABI flag.

Move build options to their own file

---

src/wx/config/internal/option-internal.cpp
src/wx/config/option-id.h
src/wx/config/option-proxy.h
src/wx/dialogs/joypad-config.cpp
src/wx/dialogs/joypad-config.h
src/wx/widgets/sdljoy.cpp
src/wx/wxvbam.h
src/wx/xrc/JoypadConfig.xrc

Add a toggle for SDL GameController Mode in the game key configuration dialog, default enabled.
On check or uncheck, change the option and reinitialize joysticks, not using GameController mode if it is disabled.

Add toggle: SDL GameController mode for joysticks

---

cmake/Toolchain-gcc-clang.cmake
src/sdl/expr-lex.cpp

Add -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing to compile and link options for gcc/clang always.
Rename struct yy_buffer_state in src/sdl/expr-lex.cpp to struct yy_buffer_state_sdl because it breaks when linking the SDL binary with -Werror=odr.
Fix #1260

build: fix LTO on Linux

---

src/wx/gfxviewers.cpp
src/wx/viewers.cpp

Some of the viewers dialogs were not properly set up and were causing a crash at runtime.

[Dialogs] Prevent viewers from causing a crash

---

doc/DevInfo.txt
src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/config/internal/option-internal.cpp
src/wx/config/internal/option-internal.h
src/wx/config/option-id.h
src/wx/config/option-proxy.h
src/wx/config/option.cpp
src/wx/config/option.h
src/wx/dialogs/display-config.cpp
src/wx/dialogs/sound-config.cpp
src/wx/dialogs/sound-config.h
src/wx/dsound.cpp
src/wx/faudio.cpp
src/wx/guiinit.cpp
src/wx/openal.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/widgets/option-validator.cpp
src/wx/widgets/option-validator.h
src/wx/wxhead.h
src/wx/wxutil.cpp
src/wx/wxvbam.h
src/wx/xaudio2.cpp
src/wx/xrc/MainMenu.xrc
src/wx/xrc/SoundConfig.xrc

This fixes a number of issues with the current implementation. Namely, some options were not properly saved and the audio driver was not properly reloaded when some options were changed.
In addition, this moves most sound-related options to `g_owned_opts` and simplifies many call sites.

[Dialogs] Move SoundConfig dialog to its own class

---

src/wx/CMakeLists.txt
src/wx/faudio.cpp

This begins the rework of the faudio code begin with removing a good deal of the imme code that the driver used to poll audio interfaces
Removed the use of HRESULT code since that's more windowisms.
Also adapted more of the faudio stuff like WaveFormatEx is FAudioWaveFormatEx WAVE_FORMAT_PCM is FAUDIO_FORMAT_PCM.
Also changed S_OK into R_OK but I'm pretty sure that isn't the way to go. That said and done, this is still a work in progress, but it compiles. But it doesn't initilize yet, I might need an extra set of eyes for that.

faudio.cpp: Begin rework of faudio implementation

---

src/core/gba/gba.cpp

The CPSR register needs to be restored from SPSR when switching modes. This is currently being done for all mode switches /except/ for FIQ, which is very likely just an oversight rather than intended behaviour.
This fixes the random crashing in OpenLara, as well as fixing random glitching of my own project that uses FIQ mode switches. The issue happens "at random" because it requires an interrupt to occur while in FIQ mode, and it must also fire inside a section of code that relies on the status flags (or the CPSR register in general): When exiting the interrupt exception, the CPSR register is supposed to be restored from SPSR, but this isn't being done when switching from IRQ mode back to FIQ mode, which results in CPSR (and thus the status flags) being corrupted. For example, `SUBS r0, …

[GBA] Set cpsr=spsr when switching to FIQ mode

---

src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/dialogs/accel-config.cpp
src/wx/dialogs/accel-config.h
src/wx/dialogs/base-dialog.cpp
src/wx/dialogs/base-dialog.h
src/wx/dialogs/directories-config.cpp
src/wx/dialogs/directories-config.h
src/wx/dialogs/display-config.cpp
src/wx/dialogs/display-config.h
src/wx/dialogs/game-boy-config.cpp
src/wx/dialogs/game-boy-config.h
src/wx/dialogs/gb-rom-info.cpp
src/wx/dialogs/gb-rom-info.h
src/wx/dialogs/joypad-config.cpp
src/wx/dialogs/joypad-config.h
src/wx/dialogs/sound-config.cpp
src/wx/dialogs/sound-config.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/sys.cpp
src/wx/viewers.cpp
src/wx/widgets/keep-on-top-styler.h
src/wx/widgets/utils.cpp
src/wx/widgets/utils.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This changes most dialogs in the wx frontend to use a common base abstraction, `dialogs::BaseDialog`. This base class sets up common style options for every dialog and automatically saves and restores the dialog position.
In addition, this moves the first time show position of the dialog to be slightly to the bottom and right of the main window, even if the main window is on a screen other than the main screen.

[Dialogs] Save and restore dialog positions

---

src/wx/config/game-control.cpp
src/wx/config/game-control.h
src/wx/config/internal/option-internal.cpp
src/wx/config/shortcuts.cpp
src/wx/config/shortcuts.h
src/wx/dialogs/accel-config.cpp
src/wx/dialogs/accel-config.h
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/opts.h
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/widgets/user-input-ctrl.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

Previously, some input-related configuration objects were either owned by `gopts` or global values. This moves these objects to be owned by the app object instead.
Rather than directly accessing the app object, other objects (like dialogs) that need to access the input-related configuration objects are passed a `ConfigurationObjectProvider` function. This will make it easier to test these objects independently down the line.
Bug: #745

[Input] Move input configuration objects to app

---

src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/config/cmdtab.cpp
src/wx/config/cmdtab.h
src/wx/config/command.cpp
src/wx/copy-events.cmake
src/wx/dialogs/accel-config.cpp
src/wx/guiinit.cpp
src/wx/opts.cpp
src/wx/panel.cpp
src/wx/sys.cpp
src/wx/widgets/client-data.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h
src/wx/xrc/AccelConfig.xrc

* Moves cmdtab to config/. This removes the dependency on the wxvbam.h header from the config/ directory.
* Fixes a number of issues in the shortcuts configuration window:
* The "Remove" command was not working properly due to an incorrect refactor.
* The window is now fully expandable.

Move cmdtab and command enable flags to config/

---

src/wx/panel.cpp
src/wx/widgets/sdl-poller.cpp
src/wx/widgets/user-input-ctrl.cpp
src/wx/widgets/user-input-ctrl.h
src/wx/widgets/user-input-event.cpp
src/wx/widgets/user-input-event.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

This modifies the UserInputEvent class to fire a vector of events at once, rather than individual down/up events for each UserInput. This simplifies handling of the global event filter and prevents the firing of spurious events.
This also fixes a bug when pressing "Ctrl+1" would trigger the command for both the command assigned to "Ctrl+1" and to "1". Now, only the "Ctrl+1" command will fire.

[UserInput] Only process shortcut commands once

---

src/wx/CMakeLists.txt
src/wx/config/user-input.cpp
src/wx/config/user-input.h
src/wx/panel.cpp
src/wx/viewsupt.cpp
src/wx/viewsupt.h
src/wx/widgets/event-handler-provider.h
src/wx/widgets/sdl-poller.cpp
src/wx/widgets/sdl-poller.h
src/wx/widgets/shortcut-menu-bar.cpp
src/wx/widgets/shortcut-menu-bar.h
src/wx/widgets/user-input-ctrl.cpp
src/wx/widgets/user-input-event.cpp
src/wx/widgets/user-input-event.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h
src/wx/xrc/MainMenu.xrc

This changes key events to be filtered globally by the application, preventing any widget from accessing them. Widgets should instead use the new VBAM_USER_INPUT_EVENT event.
In addition, this explicitly removes accelerator handling from wxWidgets main menu, allowing us to populate joystick options in the menu without firing wxWidgets assertions.

[UserInput] Filter key events globally

---

src/wx/CMakeLists.txt
src/wx/config/CMakeLists.txt
src/wx/test/CMakeLists.txt

Breaking the main wx target down to multiple libraries had the side effect that many build options were not properly applied to libraries. This fixes the issue by having a common configuration function in CMake to share most of the configuration between all of the wx-related targets.

[Build] Share wx-related targets configuration

---

.github/workflows/visual-studio-build.yml

Upstream GitHub actions now use a single toolchain version. Fixes #1297

[CI] Remove workaround for MSVC CI

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml

Update dead links from old domain `vba-m.com` to `visualboyadvance-m.org`

Migrate vba-m.com links in .github folder

---

src/wx/CMakeLists.txt
src/wx/config/option-proxy.h
src/wx/widgets/CMakeLists.txt
src/wx/widgets/test/widgets-test.cpp
src/wx/widgets/user-input-ctrl-test.cpp
src/wx/widgets/user-input-ctrl.cpp
src/wx/widgets/user-input-ctrl.h
src/wx/wxvbam.cpp

Previously, `wxEVT_KEY_DOWN` and `wxEVT_KEY_UP` were transformed into `VBAM_EVT_USER_INPUT` and marked as processed early. This broke a number of controls that rely on the traditional widgets events.
To fix this, we now filter the `wxEVT_KEY_*` and `wxEVT_CHAR` events in the only widget we use that cares about them, `UserInputCtrl` instead of filtering them at the application level.

Propagate key events

---

src/wx/audio/internal/faudio.cpp
src/wx/config/strutils-test.cpp
src/wx/config/strutils.cpp
src/wx/config/strutils.h

On Windows, wchar_t is 16 bits and represents UTF-16 code units. However, on other platforms, wchar_t is typically implemented as 32 bits to represent UTF-32 code units. In order to work around this problem, we always convert the string we get from FAudio, which is represented as UTF-16 code units, into UTF-8 and let wxString handle the conversion to its native type internally.

[FAudio] Always convert UTF-16 names

---

src/wx/dialogs/accel-config.cpp
src/wx/dialogs/base-dialog.cpp
src/wx/dialogs/base-dialog.h

This is currently broken on Wayland, resulting in dialogs showing up in random locations.

Disable dialog position save/restore on wxGTK

---

src/wx/opts.cpp
src/wx/wxvbam.cpp

Shortcuts were mistakenly written in `Keyboard/Keyboard` rather than in the `Keyboard` section.
In addition, this properly fixes toggling checkable menu item options via a shortcut.
Fixes #1334

Write shortcuts in the proper section

---

src/wx/dialogs/accel-config.cpp
src/wx/wxvbam.h
src/wx/xrc/AccelConfig.xrc

Calling `ExpandAll()` on the `wxTreeCtrl` would cause it to display outside of its intended view, hiding other controls. Instead, this sets a minimum size for the tree control, so the default window size is reasonable.
Fixes #1348

[dialogs] Display all controls in AccelConfig on Mac

---

cmake/Toolchain-gcc-clang.cmake
src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

Tracking whether or not the menus are opened is necessary on Windows since menus stop the main loop. This is not necessary on other platforms. In particular, on Mac, we do not get a `wxEVT_MENU_CLOSE` event when opening a dialog from a shortcut, resulting in the menu status tracking being incorrect.
Fixes #1348

Disable open menu tracking outside of Windows

---

src/core/gba/gbaCpuThumb.cpp

The Wii U VC emulator incorrectly allows for armv6 thumb instructions (like LSRS). These cause an undefined instruction error on real hardware but the Wii U VC emulator just ignores them. This change mimicks the Wii U VC emulator behavior.

Ignore illegal opcodes used by Wii U VC

---

src/wx/config/copy-events.cmake
src/wx/widgets/CMakeLists.txt
src/wx/widgets/keyboard-input-handler-test.cpp
src/wx/widgets/keyboard-input-handler.cpp
src/wx/widgets/keyboard-input-handler.h
src/wx/widgets/user-input-event-test.cpp
src/wx/widgets/user-input-event.cpp
src/wx/widgets/user-input-event.h
src/wx/wxvbam.cpp
src/wx/wxvbam.h

When pressing Alt+Tab, the "Alt" and "Tab" keys were considered in the "pressed" state until the user pressed them again because the window is no longer receiving keyboard events. This resulted in some shortcuts no longer working, since "Alt" was always in the pressed state. This changes the keyboard tracking to be reset when the application loses focus, fixing the issue.
This change also adds tests for the keyboard tracking.

[Input] Reset keyboard tracking on focus loss

---

src/core/base/system.h
src/core/gb/gb.cpp
src/gb-over.ini
src/libretro/libretro.cpp
src/sdl/ConfigManager.cpp
src/wx/CMakeLists.txt
src/wx/cmdevents.cpp
src/wx/config/internal/option-internal.cpp
src/wx/panel.cpp
src/wx/wxvbam.cpp
src/wx/wxvbam.h

Alleyway is a buggy game that does not work properly when a Game Boy Printer is connected. In order to work around this issue, this adds upport for built-in per-software Game Boy overrides. In addition, this renames various variables to make their meaning clearer.
* This only supports built-in overrides. External INI files are not supported.
* Only the Game Boy Printer option is supported, this only takes effect on game startup and the general configuration option is restored when the game is unloaded.
* As a result, it is possible to override the per-game override by manually setting the option while the game is running, this is working as intended.
* Future refactors of the option handling will manage overrides better.
Fixes #1368

[GB] Add support for per-game overrides

---

.gitmodules
CMakeLists.txt

Some Linux distributions use a hermetic build environment to build. This resulted in issues with `FetchContent` attempting to download googletest at configure time.
This fixes the issue by integrating googletest as a git submodule instead of downloading it at configure time.

[gtest] Use googletest as a submodule

---

src/wx/panel.cpp

On startup, the internal emulator sound volume is set to 100%. The user value in the wx frontend is not used until the emulator volume slider is modified, resulting in games starting with volume at 100% on startup.
This fixes #1407 by always setting the internal emulator sound volume on game startup.

[Sound] Set volume on game startup

---

cmake/Options.cmake
default.nix

SFML 2 no longer compiles with a modern compiler and we are blocked on SFML 3 being available in vcpkg to fix it. There is no easy way to backport fixes to SFML 2 so disable link for the time being.

[build] Disable link

---

src/wx/wxvbam.cpp
src/wx/wxvbam.h

This prevents wxWidgets from triggering the alert sound on macOS. There should be no side effect from this.
Fixes #1384

Mark `wxEVT_KEY_DOWN` as processed in `wxvbamApp`

---

src/wx/CMakeLists.txt

sometimes the infozip_binaries_win32.zip file can fail to download completely creating a wrong sized or 0MB file that fails as the following
1> [CMake] Exception calling "ExtractToDirectory" with "2" argument(s): "Central Directory corrupt."
1> [CMake] At line:1 char:53
1> [CMake] + ... ileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('C:/Users/Ho ...
1> [CMake] +                 ~~~~~~~~~~~~~
1> [CMake]     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
1> [CMake]     + FullyQualifiedErrorId : InvalidDataException
this results in the inability to build successfully, with the following.
> build\x64-static-Debug\src\wx\wxvbam.xrs" wxvbam.xrs$xrc_AccelConfig.xrc wxvbam.xrs$xrc_CheatAdd.xrc wxvbam.xrs$xrc_CheatCreate.xrc wxvbam.xrs$xrc_CheatEdit.xrc …

prevent the zip program from being incompletely downloaded

---

src/wx/panel.cpp

don't run Color Correct on SGB Hardware, Run GBA Color correct on GBC games running in GBA Hardware.

nitpicky lcd correction changes
